/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::models;
use super::{Error, configuration};

/// struct for passing parameters to the method [`list_companies`]
#[derive(Clone, Debug)]
pub struct ListCompaniesParams {
    pub limit: Option<i32>,
    pub offset: Option<i32>,
    pub domain: Option<String>,
    pub name: Option<String>,
    pub website: Option<String>,
    pub sort: Option<String>,
    pub order: Option<String>
}


/// struct for typed errors of method [`list_companies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCompaniesError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}


/// Returns a bounded company list with optional domain, name, website and sort filters. Pagination uses limit and offset; there is no response cursor.
pub async fn list_companies(configuration: &configuration::Configuration, params: ListCompaniesParams) -> Result<models::CompanyList, Error<ListCompaniesError>> {

    let uri_str = format!("{}/v1/companies", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.domain {
        req_builder = req_builder.query(&[("domain", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.website {
        req_builder = req_builder.query(&[("website", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

