/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`delete_email`]
#[derive(Clone, Debug)]
pub struct DeleteEmailParams {
    pub email: String
}

/// struct for passing parameters to the method [`list_email_mentions`]
#[derive(Clone, Debug)]
pub struct ListEmailMentionsParams {
    pub email: String,
    pub limit: Option<i32>,
    pub cursor: Option<String>,
    /// Overrides the query limit, then bounded to 1–500.
    pub x_lr_limit: Option<i32>,
    /// Overrides the query cursor.
    pub x_lr_cursor: Option<String>
}

/// struct for passing parameters to the method [`list_emails`]
#[derive(Clone, Debug)]
pub struct ListEmailsParams {
    pub domain: String,
    pub limit: Option<i32>,
    pub offset: Option<i32>,
    pub cursor: Option<String>,
    pub sources_limit: Option<i32>,
    pub only_if_free: Option<String>,
    /// Overrides the query cursor.
    pub x_lr_cursor: Option<String>,
    /// Page size; capped by the query limit when both are provided.
    pub x_lr_limit: Option<i32>
}

/// struct for passing parameters to the method [`reveal_email`]
#[derive(Clone, Debug)]
pub struct RevealEmailParams {
    pub email: String,
    pub limit: Option<i32>,
    /// Overrides the query limit, then bounded to 1–500.
    pub x_lr_limit: Option<i32>
}

/// struct for passing parameters to the method [`reveal_email_by_id`]
#[derive(Clone, Debug)]
pub struct RevealEmailByIdParams {
    pub id: String,
    pub limit: Option<i32>,
    /// Overrides the query limit, then bounded to 1–500.
    pub x_lr_limit: Option<i32>
}


/// struct for typed errors of method [`delete_email`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteEmailError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_email_mentions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEmailMentionsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_emails`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEmailsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status402(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`reveal_email`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevealEmailError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status402(models::ApiError),
    Status403(models::ApiError),
    Status404(models::EmailNotFoundError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`reveal_email_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevealEmailByIdError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status402(models::ApiError),
    Status403(models::ApiError),
    Status404(models::EmailNotFoundError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}


/// Deletes the email and its mentions. deleted is false when no email row was removed. This changes stored data and must not be retried automatically.
pub async fn delete_email(configuration: &configuration::Configuration, params: DeleteEmailParams) -> Result<models::DeleteEmailResponse, Error<DeleteEmailError>> {

    let uri_str = format!("{}/v1/emails/{email}", configuration.base_path, email=crate::apis::urlencode(params.email));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteEmailResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteEmailResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteEmailError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Returns a cursor page of source mentions. X-LR-Cursor and X-LR-Limit override query values. A full page can carry a cursor even if the next page is empty; continue until nextCursor is null.
pub async fn list_email_mentions(configuration: &configuration::Configuration, params: ListEmailMentionsParams) -> Result<models::EmailMentionsPage, Error<ListEmailMentionsError>> {

    let uri_str = format!("{}/v1/emails/{email}/mentions", configuration.base_path, email=crate::apis::urlencode(params.email));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_lr_limit {
        req_builder = req_builder.header("x-lr-limit", param_value.to_string());
    }
    if let Some(param_value) = params.x_lr_cursor {
        req_builder = req_builder.header("x-lr-cursor", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EmailMentionsPage`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EmailMentionsPage`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListEmailMentionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Lists emails and optional sources. This request may consume credits even though it uses GET. The nextCursor value is null at the end. X-LR-Cursor overrides cursor; when both limits are present, the smaller limit applies. Do not automatically retry a failed or interrupted request.
pub async fn list_emails(configuration: &configuration::Configuration, params: ListEmailsParams) -> Result<models::EmailPage, Error<ListEmailsError>> {

    let uri_str = format!("{}/v1/emails", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("domain", &params.domain.to_string())]);
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.sources_limit {
        req_builder = req_builder.query(&[("sourcesLimit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.only_if_free {
        req_builder = req_builder.query(&[("onlyIfFree", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_lr_cursor {
        req_builder = req_builder.header("x-lr-cursor", param_value.to_string());
    }
    if let Some(param_value) = params.x_lr_limit {
        req_builder = req_builder.header("x-lr-limit", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EmailPage`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EmailPage`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListEmailsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Reveals an email profile with a bounded list of mentions and may create a team lead. May spend credits despite using GET. A 404 uses a nested error object. Do not automatically retry an interrupted request.
pub async fn reveal_email(configuration: &configuration::Configuration, params: RevealEmailParams) -> Result<models::EmailRevealResponse, Error<RevealEmailError>> {

    let uri_str = format!("{}/v1/emails/{email}", configuration.base_path, email=crate::apis::urlencode(params.email));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_lr_limit {
        req_builder = req_builder.header("x-lr-limit", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EmailRevealResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EmailRevealResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RevealEmailError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Reveals an email profile by its stable ID with a bounded list of mentions. May spend credits and create a lead. A 404 uses a nested error object. Do not automatically retry.
pub async fn reveal_email_by_id(configuration: &configuration::Configuration, params: RevealEmailByIdParams) -> Result<models::EmailRevealResponse, Error<RevealEmailByIdError>> {

    let uri_str = format!("{}/v1/emails/id/{id}", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_lr_limit {
        req_builder = req_builder.header("x-lr-limit", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EmailRevealResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EmailRevealResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RevealEmailByIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

