/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::models;
use super::{Error, configuration};

/// struct for passing parameters to the method [`get_email_insights`]
#[derive(Clone, Debug)]
pub struct GetEmailInsightsParams {
    pub email: String
}


/// struct for typed errors of method [`get_email_insights`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEmailInsightsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}


/// Extracts page mentions and platform findings. JSON returns the aggregate. Accept: text/event-stream selects events discriminated by kind; final carries response and error is terminal. mention_error is an item failure and does not terminate the stream. This executes extraction work despite using GET; do not retry or reconnect automatically. Stream disconnection does not imply that backend work has been cancelled.
pub async fn get_email_insights(configuration: &configuration::Configuration, params: GetEmailInsightsParams) -> Result<models::InsightsResponse, Error<GetEmailInsightsError>> {

    let uri_str = format!("{}/v1/insights/{email}", configuration.base_path, email=crate::apis::urlencode(params.email));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

