/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::models;
use super::{Error, configuration};

/// struct for passing parameters to the method [`bind_typeform_form`]
#[derive(Clone, Debug)]
pub struct BindTypeformFormParams {
    pub team_id: String,
    pub bind_typeform_form_request: models::BindTypeformFormRequest
}

/// struct for passing parameters to the method [`bind_webflow_form`]
#[derive(Clone, Debug)]
pub struct BindWebflowFormParams {
    pub team_id: String,
    pub bind_webflow_form_request: models::BindWebflowFormRequest
}

/// struct for passing parameters to the method [`cancel_integration_job`]
#[derive(Clone, Debug)]
pub struct CancelIntegrationJobParams {
    pub team_id: String,
    pub job_id: String
}

/// struct for passing parameters to the method [`configure_airtable_mapping`]
#[derive(Clone, Debug)]
pub struct ConfigureAirtableMappingParams {
    pub team_id: String,
    pub connection_id: String,
    pub configure_airtable_mapping_request: models::ConfigureAirtableMappingRequest
}

/// struct for passing parameters to the method [`configure_coda`]
#[derive(Clone, Debug)]
pub struct ConfigureCodaParams {
    pub team_id: String,
    pub configure_coda_request: models::ConfigureCodaRequest
}

/// struct for passing parameters to the method [`configure_crm_mapping`]
#[derive(Clone, Debug)]
pub struct ConfigureCrmMappingParams {
    pub team_id: String,
    pub connection_id: String,
    pub configure_crm_mapping_request: models::ConfigureCrmMappingRequest
}

/// struct for passing parameters to the method [`configure_crm_sync`]
#[derive(Clone, Debug)]
pub struct ConfigureCrmSyncParams {
    pub team_id: String,
    pub connection_id: String,
    pub configure_crm_sync_request: models::ConfigureCrmSyncRequest
}

/// struct for passing parameters to the method [`configure_freshsales`]
#[derive(Clone, Debug)]
pub struct ConfigureFreshsalesParams {
    pub team_id: String,
    pub configure_freshsales_request: models::ConfigureFreshsalesRequest
}

/// struct for passing parameters to the method [`configure_notification_routes`]
#[derive(Clone, Debug)]
pub struct ConfigureNotificationRoutesParams {
    pub team_id: String,
    pub connection_id: String,
    pub configure_notification_routes_request: models::ConfigureNotificationRoutesRequest
}

/// struct for passing parameters to the method [`configure_slack_destination`]
#[derive(Clone, Debug)]
pub struct ConfigureSlackDestinationParams {
    pub team_id: String,
    pub connection_id: String,
    pub configure_slack_destination_request: models::ConfigureSlackDestinationRequest
}

/// struct for passing parameters to the method [`configure_teams_workflow`]
#[derive(Clone, Debug)]
pub struct ConfigureTeamsWorkflowParams {
    pub team_id: String,
    pub configure_teams_workflow_request: models::ConfigureTeamsWorkflowRequest
}

/// struct for passing parameters to the method [`configure_typeform_form`]
#[derive(Clone, Debug)]
pub struct ConfigureTypeformFormParams {
    pub team_id: String,
    pub configure_typeform_form_request: models::ConfigureTypeformFormRequest
}

/// struct for passing parameters to the method [`configure_warehouse`]
#[derive(Clone, Debug)]
pub struct ConfigureWarehouseParams {
    pub team_id: String,
    pub configure_warehouse_request: models::ConfigureWarehouseRequest
}

/// struct for passing parameters to the method [`configure_webflow_form`]
#[derive(Clone, Debug)]
pub struct ConfigureWebflowFormParams {
    pub team_id: String,
    pub configure_webflow_form_request: models::ConfigureWebflowFormRequest
}

/// struct for passing parameters to the method [`disable_mcp_identity`]
#[derive(Clone, Debug)]
pub struct DisableMcpIdentityParams {
    pub team_id: String,
    pub identity_id: String
}

/// struct for passing parameters to the method [`execute_integration_capability`]
#[derive(Clone, Debug)]
pub struct ExecuteIntegrationCapabilityParams {
    pub capability: String,
    pub execute_integration_capability_request: models::ExecuteIntegrationCapabilityRequest,
    /// Optional origin signing profile. If any origin header is present, all five are required.
    pub x_lumenreach_integration: Option<String>,
    /// Required together with the other Segment origin headers when origin signing is used.
    pub x_lumenreach_install_id: Option<String>,
    /// Required together with the other Segment origin headers when origin signing is used.
    pub x_lumenreach_timestamp: Option<String>,
    /// Required together with the other Segment origin headers when origin signing is used.
    pub x_lumenreach_event_id: Option<String>,
    /// Required together with the other Segment origin headers when origin signing is used.
    pub x_lumenreach_signature: Option<String>
}

/// struct for passing parameters to the method [`get_airtable_mapping_options`]
#[derive(Clone, Debug)]
pub struct GetAirtableMappingOptionsParams {
    pub team_id: String,
    pub connection_id: String,
    pub base_id: Option<String>
}

/// struct for passing parameters to the method [`get_crm_mapping_options`]
#[derive(Clone, Debug)]
pub struct GetCrmMappingOptionsParams {
    pub team_id: String,
    pub connection_id: String,
    pub resource_id: Option<String>
}

/// struct for passing parameters to the method [`get_hub_spot_configuration_options`]
#[derive(Clone, Debug)]
pub struct GetHubSpotConfigurationOptionsParams {
    pub team_id: String,
    pub connection_id: String
}

/// struct for passing parameters to the method [`get_integration_job`]
#[derive(Clone, Debug)]
pub struct GetIntegrationJobParams {
    pub team_id: String,
    pub job_id: String
}

/// struct for passing parameters to the method [`inspect_coda_table`]
#[derive(Clone, Debug)]
pub struct InspectCodaTableParams {
    pub team_id: String,
    pub inspect_coda_table_request: models::InspectCodaTableRequest
}

/// struct for passing parameters to the method [`inspect_excel_workbook`]
#[derive(Clone, Debug)]
pub struct InspectExcelWorkbookParams {
    pub team_id: String,
    pub inspect_excel_workbook_request: models::InspectExcelWorkbookRequest
}

/// struct for passing parameters to the method [`inspect_google_sheet`]
#[derive(Clone, Debug)]
pub struct InspectGoogleSheetParams {
    pub team_id: String,
    pub inspect_google_sheet_request: models::InspectGoogleSheetRequest
}

/// struct for passing parameters to the method [`link_mcp_identity`]
#[derive(Clone, Debug)]
pub struct LinkMcpIdentityParams {
    pub team_id: String,
    pub link_mcp_identity_request: Option<models::LinkMcpIdentityRequest>
}

/// struct for passing parameters to the method [`list_integration_connections`]
#[derive(Clone, Debug)]
pub struct ListIntegrationConnectionsParams {
    pub team_id: String
}

/// struct for passing parameters to the method [`list_integration_jobs`]
#[derive(Clone, Debug)]
pub struct ListIntegrationJobsParams {
    pub team_id: String,
    pub connection_id: Option<String>,
    pub status: Option<String>,
    pub cursor: Option<String>,
    pub limit: Option<i32>
}

/// struct for passing parameters to the method [`list_mcp_identities`]
#[derive(Clone, Debug)]
pub struct ListMcpIdentitiesParams {
    pub team_id: String
}

/// struct for passing parameters to the method [`list_sheet_workflows`]
#[derive(Clone, Debug)]
pub struct ListSheetWorkflowsParams {
    pub team_id: String
}

/// struct for passing parameters to the method [`preview_sheet_workflow`]
#[derive(Clone, Debug)]
pub struct PreviewSheetWorkflowParams {
    pub team_id: String,
    pub workflow_id: String,
    pub preview_sheet_workflow_request: Option<models::PreviewSheetWorkflowRequest>
}

/// struct for passing parameters to the method [`queue_integration_lead_export`]
#[derive(Clone, Debug)]
pub struct QueueIntegrationLeadExportParams {
    pub team_id: String,
    pub connection_id: String,
    pub queue_integration_lead_export_request: Option<models::QueueIntegrationLeadExportRequest>
}

/// struct for passing parameters to the method [`queue_notification_test`]
#[derive(Clone, Debug)]
pub struct QueueNotificationTestParams {
    pub team_id: String,
    pub connection_id: String,
    pub queue_notification_test_request: Option<models::QueueNotificationTestRequest>
}

/// struct for passing parameters to the method [`rotate_coda_credential`]
#[derive(Clone, Debug)]
pub struct RotateCodaCredentialParams {
    pub team_id: String,
    pub connection_id: String,
    pub rotate_coda_credential_request: models::RotateCodaCredentialRequest
}

/// struct for passing parameters to the method [`rotate_freshsales_credential`]
#[derive(Clone, Debug)]
pub struct RotateFreshsalesCredentialParams {
    pub team_id: String,
    pub connection_id: String,
    pub rotate_freshsales_credential_request: models::RotateFreshsalesCredentialRequest
}

/// struct for passing parameters to the method [`run_sheet_workflow`]
#[derive(Clone, Debug)]
pub struct RunSheetWorkflowParams {
    pub team_id: String,
    pub workflow_id: String,
    pub run_sheet_workflow_request: Option<models::RunSheetWorkflowRequest>
}

/// struct for passing parameters to the method [`save_sheet_workflow`]
#[derive(Clone, Debug)]
pub struct SaveSheetWorkflowParams {
    pub team_id: String,
    pub save_sheet_workflow_request: models::SaveSheetWorkflowRequest
}

/// struct for passing parameters to the method [`start_attio_o_auth`]
#[derive(Clone, Debug)]
pub struct StartAttioOAuthParams {
    pub team_id: String,
    pub start_attio_o_auth_request: Option<models::StartAttioOAuthRequest>
}

/// struct for passing parameters to the method [`start_google_sheets_o_auth`]
#[derive(Clone, Debug)]
pub struct StartGoogleSheetsOAuthParams {
    pub team_id: String,
    pub start_google_sheets_o_auth_request: Option<models::StartGoogleSheetsOAuthRequest>
}

/// struct for passing parameters to the method [`start_integration_o_auth`]
#[derive(Clone, Debug)]
pub struct StartIntegrationOAuthParams {
    pub team_id: String,
    pub provider: String,
    pub start_integration_o_auth_request: Option<models::StartIntegrationOAuthRequest>
}

/// struct for passing parameters to the method [`test_integration_connection`]
#[derive(Clone, Debug)]
pub struct TestIntegrationConnectionParams {
    pub team_id: String,
    pub connection_id: String
}

/// struct for passing parameters to the method [`update_integration_connection_state`]
#[derive(Clone, Debug)]
pub struct UpdateIntegrationConnectionStateParams {
    pub team_id: String,
    pub connection_id: String,
    pub update_integration_connection_state_request: models::UpdateIntegrationConnectionStateRequest
}

/// struct for passing parameters to the method [`update_sheet_workflow_state`]
#[derive(Clone, Debug)]
pub struct UpdateSheetWorkflowStateParams {
    pub team_id: String,
    pub workflow_id: String,
    pub update_sheet_workflow_state_request: models::UpdateSheetWorkflowStateRequest
}


/// struct for typed errors of method [`bind_typeform_form`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BindTypeformFormError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`bind_webflow_form`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BindWebflowFormError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`cancel_integration_job`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CancelIntegrationJobError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_airtable_mapping`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureAirtableMappingError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_coda`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureCodaError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_crm_mapping`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureCrmMappingError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_crm_sync`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureCrmSyncError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_freshsales`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureFreshsalesError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_notification_routes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureNotificationRoutesError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_slack_destination`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureSlackDestinationError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_teams_workflow`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureTeamsWorkflowError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_typeform_form`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureTypeformFormError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_warehouse`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureWarehouseError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`configure_webflow_form`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigureWebflowFormError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`disable_mcp_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisableMcpIdentityError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status404(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`execute_integration_capability`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExecuteIntegrationCapabilityError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_airtable_mapping_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAirtableMappingOptionsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_crm_mapping_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCrmMappingOptionsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_hub_spot_configuration_options`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetHubSpotConfigurationOptionsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_integration_job`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIntegrationJobError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`inspect_coda_table`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InspectCodaTableError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`inspect_excel_workbook`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InspectExcelWorkbookError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`inspect_google_sheet`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InspectGoogleSheetError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`link_mcp_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LinkMcpIdentityError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_integration_connections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListIntegrationConnectionsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_integration_jobs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListIntegrationJobsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_integration_providers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListIntegrationProvidersError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_mcp_identities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListMcpIdentitiesError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_sheet_workflows`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSheetWorkflowsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`preview_sheet_workflow`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PreviewSheetWorkflowError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`queue_integration_lead_export`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueueIntegrationLeadExportError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`queue_notification_test`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueueNotificationTestError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rotate_coda_credential`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RotateCodaCredentialError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rotate_freshsales_credential`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RotateFreshsalesCredentialError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`run_sheet_workflow`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RunSheetWorkflowError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`save_sheet_workflow`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SaveSheetWorkflowError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`start_attio_o_auth`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StartAttioOAuthError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`start_google_sheets_o_auth`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StartGoogleSheetsOAuthError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`start_integration_o_auth`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StartIntegrationOAuthError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`test_integration_connection`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TestIntegrationConnectionError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_integration_connection_state`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateIntegrationConnectionStateError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_sheet_workflow_state`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateSheetWorkflowStateError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status503(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}


/// Binds a form to an existing OAuth connection and configures the provider callback.
pub async fn bind_typeform_form(configuration: &configuration::Configuration, params: BindTypeformFormParams) -> Result<models::IntegrationFormConnectionResponse, Error<BindTypeformFormError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/typeform/oauth/bind", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.bind_typeform_form_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Binds a form to an existing OAuth connection and configures the provider callback.
pub async fn bind_webflow_form(configuration: &configuration::Configuration, params: BindWebflowFormParams) -> Result<models::IntegrationFormConnectionResponse, Error<BindWebflowFormError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/webflow/oauth/bind", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.bind_webflow_form_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Requires team administrator access. Cancels a pending job or requests cancellation of running work. Terminal jobs return already_terminal.
pub async fn cancel_integration_job(configuration: &configuration::Configuration, params: CancelIntegrationJobParams) -> Result<models::IntegrationJobCancellation, Error<CancelIntegrationJobError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/jobs/{jobId}/cancel", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), jobId=crate::apis::urlencode(params.job_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Validates remote fields, updates the mapping and tests the connection. Inspect test.state for provider readiness.
pub async fn configure_airtable_mapping(configuration: &configuration::Configuration, params: ConfigureAirtableMappingParams) -> Result<models::IntegrationConnectionTestResponse, Error<ConfigureAirtableMappingError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/airtable-mapping/configure", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_airtable_mapping_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Creates a mapped Coda connection and tests access. Inspect test.state for provider health.
pub async fn configure_coda(configuration: &configuration::Configuration, params: ConfigureCodaParams) -> Result<models::IntegrationConnectionTestResponse, Error<ConfigureCodaError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/coda", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_coda_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Validates provider-specific mapping, updates the connection and runs a connection test.
pub async fn configure_crm_mapping(configuration: &configuration::Configuration, params: ConfigureCrmMappingParams) -> Result<models::IntegrationConnectionTestResponse, Error<ConfigureCrmMappingError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/crm-mapping/configure", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_crm_mapping_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Validates and saves lifecycle sync policies and optional HubSpot owner/deal configuration. Returns normalized configuration.
pub async fn configure_crm_sync(configuration: &configuration::Configuration, params: ConfigureCrmSyncParams) -> Result<models::CrmSyncConfigurationResponse, Error<ConfigureCrmSyncError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/crm-sync/configure", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_crm_sync_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Creates a connection, securely stores the supplied credential and runs a connection test. Inspect test.state; HTTP success does not imply a healthy provider.
pub async fn configure_freshsales(configuration: &configuration::Configuration, params: ConfigureFreshsalesParams) -> Result<models::IntegrationConnectionTestResponse, Error<ConfigureFreshsalesError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/freshsales", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_freshsales_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Saves notification event routes for the connection.
pub async fn configure_notification_routes(configuration: &configuration::Configuration, params: ConfigureNotificationRoutesParams) -> Result<models::IntegrationConnectionResponse, Error<ConfigureNotificationRoutesError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/notification-routes", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_notification_routes_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Sets the destination channel and notification routes for a Slack connection.
pub async fn configure_slack_destination(configuration: &configuration::Configuration, params: ConfigureSlackDestinationParams) -> Result<models::IntegrationConnectionResponse, Error<ConfigureSlackDestinationError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/slack-destination", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_slack_destination_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Creates a connection using the supplied Teams webhook URL and notification routes. The credential is stored separately from public connection configuration.
pub async fn configure_teams_workflow(configuration: &configuration::Configuration, params: ConfigureTeamsWorkflowParams) -> Result<models::IntegrationConnectionResponse, Error<ConfigureTeamsWorkflowError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/microsoft-teams", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_teams_workflow_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Creates a form connection and configures its provider callback. Requires administrator access.
pub async fn configure_typeform_form(configuration: &configuration::Configuration, params: ConfigureTypeformFormParams) -> Result<models::IntegrationFormConnectionResponse, Error<ConfigureTypeformFormError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/typeform", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_typeform_form_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Creates a warehouse connection from the provider-specific configuration and credentials. Requires administrator access.
pub async fn configure_warehouse(configuration: &configuration::Configuration, params: ConfigureWarehouseParams) -> Result<models::IntegrationConnectionResponse, Error<ConfigureWarehouseError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/warehouses", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_warehouse_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Creates a form connection and configures its provider callback. Requires administrator access.
pub async fn configure_webflow_form(configuration: &configuration::Configuration, params: ConfigureWebflowFormParams) -> Result<models::IntegrationFormConnectionResponse, Error<ConfigureWebflowFormError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/webflow", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.configure_webflow_form_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Disables an identity belonging to the current user and team. Returns 204 without a response body, or 404 when no matching identity exists.
pub async fn disable_mcp_identity(configuration: &configuration::Configuration, params: DisableMcpIdentityParams) -> Result<(), Error<DisableMcpIdentityError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/mcp-identities/{identityId}", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), identityId=crate::apis::urlencode(params.identity_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.no_content()
}

/// Runs email.find, email.verify or domain.search against existing revealed/cached data without charging credits. mode defaults to live; preview returns output null. email.find input uses firstName, lastName and domain; email.verify uses email; domain.search uses domain and limit (1–100), with optional company. idempotencyKey is required by HTTP validation in both modes. replay describes invocation recording and must not be treated as permission to automatically replay execution. Segment-signed requests must supply all five origin headers and use segment:SHA256(capability + \":\" + eventId) as idempotencyKey.
pub async fn execute_integration_capability(configuration: &configuration::Configuration, params: ExecuteIntegrationCapabilityParams) -> Result<models::IntegrationCapabilityResponse, Error<ExecuteIntegrationCapabilityError>> {

    let uri_str = format!("{}/v1/actions/{capability}", configuration.base_path, capability=crate::apis::urlencode(params.capability));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_lumenreach_integration {
        req_builder = req_builder.header("x-lumenreach-integration", param_value.to_string());
    }
    if let Some(param_value) = params.x_lumenreach_install_id {
        req_builder = req_builder.header("x-lumenreach-install-id", param_value.to_string());
    }
    if let Some(param_value) = params.x_lumenreach_timestamp {
        req_builder = req_builder.header("x-lumenreach-timestamp", param_value.to_string());
    }
    if let Some(param_value) = params.x_lumenreach_event_id {
        req_builder = req_builder.header("x-lumenreach-event-id", param_value.to_string());
    }
    if let Some(param_value) = params.x_lumenreach_signature {
        req_builder = req_builder.header("x-lumenreach-signature", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.execute_integration_capability_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Lists accessible bases and, when baseId is supplied, its tables and fields. Requires administrator access.
pub async fn get_airtable_mapping_options(configuration: &configuration::Configuration, params: GetAirtableMappingOptionsParams) -> Result<models::AirtableMappingOptionsResponse, Error<GetAirtableMappingOptionsError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/airtable-mapping-options", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.base_id {
        req_builder = req_builder.query(&[("baseId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Returns provider objects and writable fields. resourceId selects a provider resource where required, such as a Notion data source.
pub async fn get_crm_mapping_options(configuration: &configuration::Configuration, params: GetCrmMappingOptionsParams) -> Result<models::CrmMappingOptionsResponse, Error<GetCrmMappingOptionsError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/crm-mapping-options", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.resource_id {
        req_builder = req_builder.query(&[("resourceId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Lists available contact owners and deal pipelines with their stages. Requires a HubSpot connection and administrator access.
pub async fn get_hub_spot_configuration_options(configuration: &configuration::Configuration, params: GetHubSpotConfigurationOptionsParams) -> Result<models::HubSpotConfigurationOptionsResponse, Error<GetHubSpotConfigurationOptionsError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/hubspot-configuration-options", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Returns a job visible to the current user. A missing job is a 400 validation error.
pub async fn get_integration_job(configuration: &configuration::Configuration, params: GetIntegrationJobParams) -> Result<models::IntegrationJobResponse, Error<GetIntegrationJobError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/jobs/{jobId}", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), jobId=crate::apis::urlencode(params.job_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Requires team administrator access. Uses the supplied API token to discover document and table columns without saving a connection.
pub async fn inspect_coda_table(configuration: &configuration::Configuration, params: InspectCodaTableParams) -> Result<models::CodaTableInspectionResponse, Error<InspectCodaTableError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/coda/inspect", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.inspect_coda_table_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Requires a ready connection owned by the current user and exactly one of driveItemId or shareUrl. Falls back to the first visible worksheet when the requested worksheet is unavailable.
pub async fn inspect_excel_workbook(configuration: &configuration::Configuration, params: InspectExcelWorkbookParams) -> Result<models::ExcelWorkbookInspectionResponse, Error<InspectExcelWorkbookError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/microsoft-excel/inspect", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.inspect_excel_workbook_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Reads sheet names and header columns using a ready connection. headerRow defaults to 1.
pub async fn inspect_google_sheet(configuration: &configuration::Configuration, params: InspectGoogleSheetParams) -> Result<models::GoogleSheetInspectionResponse, Error<InspectGoogleSheetError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/google-sheets/inspect", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.inspect_google_sheet_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Requires X-API-Key and a separate verified OIDC token in Authorization: Bearer. Requested scopes must be a subset of the verified token scopes. Omission uses the token scopes. Returns 503 when MCP OIDC is not configured.
pub async fn link_mcp_identity(configuration: &configuration::Configuration, params: LinkMcpIdentityParams) -> Result<models::McpIdentityResponse, Error<LinkMcpIdentityError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/mcp-identities", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.link_mcp_identity_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Lists visible, non-deleted connections for the authenticated team. Credential values are not included.
pub async fn list_integration_connections(configuration: &configuration::Configuration, params: ListIntegrationConnectionsParams) -> Result<models::IntegrationConnectionList, Error<ListIntegrationConnectionsError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Lists visible jobs, optionally filtered by connection or status. The default limit is 25 and the maximum is 100. Continue until nextCursor is null.
pub async fn list_integration_jobs(configuration: &configuration::Configuration, params: ListIntegrationJobsParams) -> Result<models::IntegrationJobPage, Error<ListIntegrationJobsError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/jobs", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.connection_id {
        req_builder = req_builder.query(&[("connectionId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Lists provider metadata, readiness and supported capabilities. Provider identifiers and response status fields remain extensible.
pub async fn list_integration_providers(configuration: &configuration::Configuration) -> Result<models::IntegrationProviderList, Error<ListIntegrationProvidersError>> {

    let uri_str = format!("{}/v1/integrations/providers", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Returns up to 100 identities belonging to this user and team.
pub async fn list_mcp_identities(configuration: &configuration::Configuration, params: ListMcpIdentitiesParams) -> Result<models::McpIdentityList, Error<ListMcpIdentitiesError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/mcp-identities", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Returns up to 100 workflows visible to this user. Provider ownership and team administrator rules apply.
pub async fn list_sheet_workflows(configuration: &configuration::Configuration, params: ListSheetWorkflowsParams) -> Result<models::SheetWorkflowList, Error<ListSheetWorkflowsError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/spreadsheet-workflows", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Reads rows and validates the layout without executing the capability. Also updates workflow validation state. rowLimit defaults to 20 and is bounded to 1–50.
pub async fn preview_sheet_workflow(configuration: &configuration::Configuration, params: PreviewSheetWorkflowParams) -> Result<models::SheetWorkflowPreview, Error<PreviewSheetWorkflowError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/spreadsheet-workflows/{workflowId}/preview", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), workflowId=crate::apis::urlencode(params.workflow_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.preview_sheet_workflow_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Queues selected leads for provider export and returns their count. Supply a stable requestId for request identification. A 202 response acknowledges queuing; poll getIntegrationJob for completion.
pub async fn queue_integration_lead_export(configuration: &configuration::Configuration, params: QueueIntegrationLeadExportParams) -> Result<models::IntegrationLeadExportResponse, Error<QueueIntegrationLeadExportError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/export-leads", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.queue_integration_lead_export_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Queues a provider test notification and returns 202. Poll getIntegrationJob for completion. This can send a message to the configured destination.
pub async fn queue_notification_test(configuration: &configuration::Configuration, params: QueueNotificationTestParams) -> Result<models::QueuedIntegrationJobResponse, Error<QueueNotificationTestError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/notification-test", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.queue_notification_test_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Stages and tests the replacement API token before completing rotation.
pub async fn rotate_coda_credential(configuration: &configuration::Configuration, params: RotateCodaCredentialParams) -> Result<models::IntegrationConnectionTestResponse, Error<RotateCodaCredentialError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/credentials/coda/rotate", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.rotate_coda_credential_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Stages and tests the replacement credential before completing rotation. Requires connection operator access.
pub async fn rotate_freshsales_credential(configuration: &configuration::Configuration, params: RotateFreshsalesCredentialParams) -> Result<models::IntegrationConnectionTestResponse, Error<RotateFreshsalesCredentialError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/credentials/freshsales/rotate", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.rotate_freshsales_credential_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Queues writeback and returns 202, not completion. Supply a stable requestId to identify this workflow revision and request; omission creates a new request ID. Poll getIntegrationJob for completion.
pub async fn run_sheet_workflow(configuration: &configuration::Configuration, params: RunSheetWorkflowParams) -> Result<models::QueuedIntegrationJobResponse, Error<RunSheetWorkflowError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/spreadsheet-workflows/{workflowId}/run", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), workflowId=crate::apis::urlencode(params.workflow_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.run_sheet_workflow_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Creates a workflow with 201, or updates the supplied workflowId with 200. The configuration is validated for its spreadsheet provider and capability.
pub async fn save_sheet_workflow(configuration: &configuration::Configuration, params: SaveSheetWorkflowParams) -> Result<models::SheetWorkflowResponse, Error<SaveSheetWorkflowError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/spreadsheet-workflows", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.save_sheet_workflow_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Creates an authorization transaction and returns its URL and expiry. Complete consent in a browser.
pub async fn start_attio_o_auth(configuration: &configuration::Configuration, params: StartAttioOAuthParams) -> Result<models::IntegrationOAuthStartResponse, Error<StartAttioOAuthError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/attio/oauth/start", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.start_attio_o_auth_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Creates a short-lived authorization transaction. Open authorizationUrl in a browser to complete provider consent before using the resulting connection.
pub async fn start_google_sheets_o_auth(configuration: &configuration::Configuration, params: StartGoogleSheetsOAuthParams) -> Result<models::IntegrationOAuthStartResponse, Error<StartGoogleSheetsOAuthError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/google-sheets/oauth/start", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.start_google_sheets_o_auth_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Starts authorization for the supported provider. Complete consent at authorizationUrl before configuring the connection. Provider-specific authorizationServer and resourceUrl inputs are validated by the server.
pub async fn start_integration_o_auth(configuration: &configuration::Configuration, params: StartIntegrationOAuthParams) -> Result<models::IntegrationOAuthStartResponse, Error<StartIntegrationOAuthError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/{provider}/oauth/start", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), provider=crate::apis::urlencode(params.provider));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.start_integration_o_auth_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Calls the provider and updates connection health. Inspect test.state and test.code; provider test failure may be represented in a successful HTTP response.
pub async fn test_integration_connection(configuration: &configuration::Configuration, params: TestIntegrationConnectionParams) -> Result<models::IntegrationConnectionTestResponse, Error<TestIntegrationConnectionError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/test", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Pauses, resumes or disconnects a connection. vaultDeletionPending counts credential deletions still pending cleanup.
pub async fn update_integration_connection_state(configuration: &configuration::Configuration, params: UpdateIntegrationConnectionStateParams) -> Result<models::IntegrationConnectionStateResponse, Error<UpdateIntegrationConnectionStateError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/connections/{connectionId}/state", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), connectionId=crate::apis::urlencode(params.connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.update_integration_connection_state_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

/// Pauses, resumes or deletes the workflow. Delete returns deleted and workflowId; pause and resume return the workflow.
pub async fn update_sheet_workflow_state(configuration: &configuration::Configuration, params: UpdateSheetWorkflowStateParams) -> Result<models::SheetWorkflowStateResponse, Error<UpdateSheetWorkflowStateError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/integrations/spreadsheet-workflows/{workflowId}/state", configuration.base_path, teamId=crate::apis::urlencode(params.team_id), workflowId=crate::apis::urlencode(params.workflow_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.update_sheet_workflow_state_request);

    let req = req_builder.build()?;
    let resp = crate::http_policy::execute(configuration, req).await?;

    resp.json()
}

