/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`create_lead`]
#[derive(Clone, Debug)]
pub struct CreateLeadParams {
    pub team_id: String,
    pub create_lead_request: models::CreateLeadRequest
}

/// struct for passing parameters to the method [`delete_lead`]
#[derive(Clone, Debug)]
pub struct DeleteLeadParams {
    pub lead_id: String
}

/// struct for passing parameters to the method [`export_leads`]
#[derive(Clone, Debug)]
pub struct ExportLeadsParams {
    pub team_id: String,
    pub export_leads_request: models::ExportLeadsRequest
}

/// struct for passing parameters to the method [`get_lead`]
#[derive(Clone, Debug)]
pub struct GetLeadParams {
    pub lead_id: String
}

/// struct for passing parameters to the method [`list_leads`]
#[derive(Clone, Debug)]
pub struct ListLeadsParams {
    pub team_id: String,
    pub limit: Option<i32>,
    pub offset: Option<i32>,
    pub cursor: Option<String>,
    pub domain: Option<String>,
    pub search: Option<String>,
    pub sort: Option<String>,
    pub group: Option<String>,
    pub order: Option<String>,
    pub position: Option<String>,
    pub filters: Option<String>
}

/// struct for passing parameters to the method [`update_lead`]
#[derive(Clone, Debug)]
pub struct UpdateLeadParams {
    pub lead_id: String,
    pub update_lead_request: Option<models::UpdateLeadRequest>
}


/// struct for typed errors of method [`create_lead`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateLeadError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_lead`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteLeadError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status404(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`export_leads`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExportLeadsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status413(models::LeadExportTooLargeError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_lead`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLeadError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status404(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_leads`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListLeadsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_lead`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateLeadError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status404(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}


/// Creates a lead for the authenticated team. An API key cannot create leads for another team. Uses HTTP 200 with a lead envelope. No idempotency key is implemented; do not automatically retry.
pub async fn create_lead(configuration: &configuration::Configuration, params: CreateLeadParams) -> Result<models::CreateLeadResponse, Error<CreateLeadError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/leads", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.create_lead_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateLeadResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateLeadResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateLeadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Deletes a lead visible to the authenticated team and returns a success envelope. A repeated delete can return 404.
pub async fn delete_lead(configuration: &configuration::Configuration, params: DeleteLeadParams) -> Result<models::DeleteLeadResponse, Error<DeleteLeadError>> {

    let uri_str = format!("{}/v1/leads/{leadId}", configuration.base_path, leadId=crate::apis::urlencode(params.lead_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteLeadResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteLeadResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteLeadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Exports leads selected by inclusion/exclusion scopes and selected/deselected IDs. The body format field selects a JSON array (default) or text/csv attachment. Oversized selections return 413. Selection scopes must contain at least one item. No automatic replay.
pub async fn export_leads(configuration: &configuration::Configuration, params: ExportLeadsParams) -> Result<Vec<models::LeadExportInner>, Error<ExportLeadsError>> {
    if params.export_leads_request.format == Some(models::export_leads_request::Format::Csv) {
        return Err(Error::Io(std::io::Error::new(std::io::ErrorKind::InvalidInput, "Use export_leads_csv for a CSV export")));
    }
    let resp = export_leads_response(configuration, params).await?;


    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::LeadExportInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::LeadExportInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExportLeadsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Download CSV text with one request; HTTP errors retain status, headers and body.
pub async fn export_leads_csv(configuration: &configuration::Configuration, mut params: ExportLeadsParams) -> Result<String, Error<ExportLeadsError>> {
    params.export_leads_request.format = Some(models::export_leads_request::Format::Csv);
    let resp = export_leads_response(configuration, params).await?;
    let status = resp.status();
    let headers = resp.headers().clone();
    let content = resp.text().await?;
    if !status.is_success() {
        let entity: Option<ExportLeadsError> = serde_json::from_str(&content).ok();
        return Err(Error::ResponseError(ResponseContent { status, headers, content, entity }));
    }
    let media_type = headers.get(reqwest::header::CONTENT_TYPE).and_then(|v|v.to_str().ok()).unwrap_or("");
    if !media_type.split(';').next().unwrap_or("").trim().eq_ignore_ascii_case("text/csv") {
        return Err(Error::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, "Expected a CSV export response")));
    }
    Ok(content)
}
async fn export_leads_response(configuration: &configuration::Configuration, params: ExportLeadsParams) -> Result<reqwest::Response, Error<ExportLeadsError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/leads/export", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    let accept = if params.export_leads_request.format == Some(models::export_leads_request::Format::Csv) { "text/csv" } else { "application/json" };
    req_builder = req_builder.header(reqwest::header::ACCEPT, accept).json(&params.export_leads_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;
    Ok(resp)
}


/// Retrieves a lead visible to the authenticated team. A missing or inaccessible lead can return 404.
pub async fn get_lead(configuration: &configuration::Configuration, params: GetLeadParams) -> Result<models::GetLeadResponse, Error<GetLeadError>> {

    let uri_str = format!("{}/v1/leads/{leadId}", configuration.base_path, leadId=crate::apis::urlencode(params.lead_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetLeadResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetLeadResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLeadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Lists leads belonging to the authenticated team, with filters, optional grouping and opaque cursors. filters is a JSON-encoded object. nextCursor, nextGroupCursor and lastGroupCursor are null when absent. The handler always returns JSON; use exportLeads for CSV.
pub async fn list_leads(configuration: &configuration::Configuration, params: ListLeadsParams) -> Result<models::LeadPage, Error<ListLeadsError>> {

    let uri_str = format!("{}/v1/teams/{teamId}/leads", configuration.base_path, teamId=crate::apis::urlencode(params.team_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.domain {
        req_builder = req_builder.query(&[("domain", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.search {
        req_builder = req_builder.query(&[("search", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.group {
        req_builder = req_builder.query(&[("group", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.position {
        req_builder = req_builder.query(&[("position", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.filters {
        req_builder = req_builder.query(&[("filters", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeadPage`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeadPage`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListLeadsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Updates a lead visible to the authenticated team and returns the updated lead envelope. This endpoint uses POST. Missing leads or an update with no changes can return 404; do not automatically replay.
pub async fn update_lead(configuration: &configuration::Configuration, params: UpdateLeadParams) -> Result<models::UpdateLeadResponse, Error<UpdateLeadError>> {

    let uri_str = format!("{}/v1/leads/{leadId}/update", configuration.base_path, leadId=crate::apis::urlencode(params.lead_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.update_lead_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateLeadResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateLeadResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateLeadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

