/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`list_name_patterns`]
#[derive(Clone, Debug)]
pub struct ListNamePatternsParams {
    pub domain: String,
    pub first: Option<String>,
    pub last: Option<String>
}

/// struct for passing parameters to the method [`verify_name`]
#[derive(Clone, Debug)]
pub struct VerifyNameParams {
    pub domain: String,
    pub first: Option<String>,
    pub last: Option<String>,
    pub cache_max_age: Option<String>,
    pub only_if_free: Option<String>
}


/// struct for typed errors of method [`list_name_patterns`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListNamePatternsError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`verify_name`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VerifyNameError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status402(models::ApiError),
    Status403(models::ApiError),
    Status422(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}


/// Returns name patterns ranked by score. domain is required and validated; optional first and last query fields do not alter this static pattern list.
pub async fn list_name_patterns(configuration: &configuration::Configuration, params: ListNamePatternsParams) -> Result<models::NamePatternsResponse, Error<ListNamePatternsError>> {

    let uri_str = format!("{}/v1/name/schemas", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("domain", &params.domain.to_string())]);
    if let Some(ref param_value) = params.first {
        req_builder = req_builder.query(&[("first", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.last {
        req_builder = req_builder.query(&[("last", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NamePatternsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NamePatternsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListNamePatternsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Verifies candidate addresses built from sanitized first and last names. JSON returns patterns, globalStages and results. With Accept: text/event-stream, events contain stages or individual pattern verdicts; ordinary completion is clean EOF, with no aggregate final marker. When no candidates can be built, the stream instead emits a result envelope and ends. Errors can describe individual candidates; an error event is not universally terminal. The operation may consume credits; never reconnect or replay automatically.
pub async fn verify_name(configuration: &configuration::Configuration, params: VerifyNameParams) -> Result<models::NameVerificationResponse, Error<VerifyNameError>> {

    let uri_str = format!("{}/v1/name/verify", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("domain", &params.domain.to_string())]);
    if let Some(ref param_value) = params.first {
        req_builder = req_builder.query(&[("first", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.last {
        req_builder = req_builder.query(&[("last", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.cache_max_age {
        req_builder = req_builder.query(&[("cacheMaxAge", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.only_if_free {
        req_builder = req_builder.query(&[("onlyIfFree", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NameVerificationResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NameVerificationResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<VerifyNameError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

