/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`execute_product_tool`]
#[derive(Clone, Debug)]
pub struct ExecuteProductToolParams {
    pub tool: String,
    pub product_tool_request: models::ProductToolRequest
}


/// struct for typed errors of method [`execute_product_tool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExecuteProductToolError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status403(models::ApiError),
    Status409(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}


/// Execute one of the listed tools using a team API key. Choose the input schema associated with the tool path parameter; the input union alone cannot express that relationship. Read tools return executionId=null and replay=false. Write tools require input.idempotencyKey (16–200 characters), scoped to the team across tools. Reusing a key with the same tool and validated input returns the committed output with replay=true while retained; different input or an unfinished execution returns HTTP 409. The SDK does not automatically retry this dispatcher. Tool scopes describe the shared integration/MCP catalog; this HTTP endpoint uses team API-key authentication and team-access checks. Missing database resources can currently surface as HTTP 500. See each tool for output and pagination semantics.
pub async fn execute_product_tool(configuration: &configuration::Configuration, params: ExecuteProductToolParams) -> Result<models::ProductToolExecution, Error<ExecuteProductToolError>> {

    let uri_str = format!("{}/v1/product/tools/{tool}", configuration.base_path, tool=crate::apis::urlencode(params.tool));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.product_tool_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ProductToolExecution`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ProductToolExecution`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExecuteProductToolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

