/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`verify_batch`]
#[derive(Clone, Debug)]
pub struct VerifyBatchParams {
    pub batch_verification_request: models::BatchVerificationRequest
}

/// struct for passing parameters to the method [`verify_email`]
#[derive(Clone, Debug)]
pub struct VerifyEmailParams {
    pub email: String,
    pub cache_max_age: Option<String>,
    pub only_if_free: Option<String>
}


/// struct for typed errors of method [`verify_batch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VerifyBatchError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`verify_email`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VerifyEmailError {
    Status400(models::ApiError),
    Status401(models::ApiError),
    Status402(models::ApiError),
    Status422(models::ApiError),
    Status429(models::ApiError),
    Status500(models::ApiError),
    Status504(models::ApiError),
    DefaultResponse(models::ApiError),
    UnknownValue(serde_json::Value),
}


/// Processes email addresses sequentially. A successful HTTP 200 response contains per-item results or errors. Do not replay the whole batch when only one item fails. This operation may consume credits.
pub async fn verify_batch(configuration: &configuration::Configuration, params: VerifyBatchParams) -> Result<models::BatchVerificationResponse, Error<VerifyBatchError>> {

    let uri_str = format!("{}/v1/verify/batch", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&params.batch_verification_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BatchVerificationResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BatchVerificationResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<VerifyBatchError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

/// Returns a final JSON aggregate by default. Accept: text/event-stream selects a finite stream of unnamed data events. Events carry a stage, state, result or error; there is no kind field or [DONE] marker on this endpoint. A result or error is terminal. Verification may consume credits and must not be automatically retried or reconnected.
pub async fn verify_email(configuration: &configuration::Configuration, params: VerifyEmailParams) -> Result<models::VerificationResponse, Error<VerifyEmailError>> {

    let uri_str = format!("{}/v1/verify", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("email", &params.email.to_string())]);
    if let Some(ref param_value) = params.cache_max_age {
        req_builder = req_builder.query(&[("cacheMaxAge", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.only_if_free {
        req_builder = req_builder.query(&[("onlyIfFree", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let headers = resp.headers().clone();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VerificationResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VerificationResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<VerifyEmailError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, headers, content, entity }))
    }
}

