/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyIdentity {
    #[serde(rename = "keyId")]
    pub key_id: String,
    #[serde(rename = "teamId")]
    pub team_id: String,
}

impl ApiKeyIdentity {
    pub fn new(key_id: String, team_id: String) -> ApiKeyIdentity {
        ApiKeyIdentity {
            key_id,
            team_id,
        }
    }
}

