/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutomationHookCreated {
    #[serde(rename = "callbackUrl")]
    pub callback_url: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "event")]
    pub event: String,
    #[serde(rename = "id")]
    pub id: String,
    /// Signing secret returned on creation. Store securely; redact from examples and logs.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl AutomationHookCreated {
    pub fn new(callback_url: String, created_at: String, event: String, id: String, secret: String) -> AutomationHookCreated {
        AutomationHookCreated {
            callback_url,
            created_at,
            event,
            id,
            secret,
        }
    }
}

