/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapabilityEmailVerified {
    #[serde(rename = "checkedAt")]
    pub checked_at: String,
    #[serde(rename = "details")]
    pub details: models::CapabilityEmailVerifiedDetails,
    #[serde(rename = "freshness")]
    pub freshness: String,
    #[serde(rename = "score")]
    pub score: f64,
    #[serde(rename = "sources")]
    pub sources: i32,
    #[serde(rename = "status")]
    pub status: String,
}

impl CapabilityEmailVerified {
    pub fn new(checked_at: String, details: models::CapabilityEmailVerifiedDetails, freshness: String, score: f64, sources: i32, status: String) -> CapabilityEmailVerified {
        CapabilityEmailVerified {
            checked_at,
            details,
            freshness,
            score,
            sources,
            status,
        }
    }
}

