/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapabilityEmailFound {
    #[serde(rename = "confidence")]
    pub confidence: f64,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "freshness")]
    pub freshness: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl CapabilityEmailFound {
    pub fn new(confidence: f64, email: String, freshness: String, status: String) -> CapabilityEmailFound {
        CapabilityEmailFound {
            confidence,
            email,
            freshness,
            status,
        }
    }
}

