/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapabilityDomainSearch {
    #[serde(rename = "contacts")]
    pub contacts: Vec<models::CapabilityDomainSearchContactsInner>,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "freshness")]
    pub freshness: String,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
}

impl CapabilityDomainSearch {
    pub fn new(contacts: Vec<models::CapabilityDomainSearchContactsInner>, domain: String, freshness: String) -> CapabilityDomainSearch {
        CapabilityDomainSearch {
            contacts,
            domain,
            freshness,
            organization: None,
        }
    }
}

