/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapabilityDomainSearchContactsInner {
    #[serde(rename = "confidence")]
    pub confidence: f64,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
}

impl CapabilityDomainSearchContactsInner {
    pub fn new(confidence: f64, email: String) -> CapabilityDomainSearchContactsInner {
        CapabilityDomainSearchContactsInner {
            confidence,
            email,
            first_name: None,
            last_name: None,
            position: None,
        }
    }
}

