/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyContextSource {
    #[serde(rename = "externalId", deserialize_with = "Option::deserialize")]
    pub external_id: Option<String>,
    #[serde(rename = "observedAt", deserialize_with = "Option::deserialize")]
    pub observed_at: Option<String>,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "url", deserialize_with = "Option::deserialize")]
    pub url: Option<String>,
}

impl CompanyContextSource {
    pub fn new(external_id: Option<String>, observed_at: Option<String>, source: String, url: Option<String>) -> CompanyContextSource {
        CompanyContextSource {
            external_id,
            observed_at,
            source,
            url,
        }
    }
}

