/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigureWarehouseRequest {
    #[serde(rename = "config")]
    pub config: std::collections::HashMap<String, String>,
    #[serde(rename = "credential")]
    pub credential: std::collections::HashMap<String, String>,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
    #[serde(rename = "provider")]
    pub provider: Provider,
}

impl ConfigureWarehouseRequest {
    pub fn new(config: std::collections::HashMap<String, String>, credential: std::collections::HashMap<String, String>, label: String, provider: Provider) -> ConfigureWarehouseRequest {
        ConfigureWarehouseRequest {
            config,
            credential,
            label,
            mode: None,
            provider,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "live")]
    Live,
    #[serde(rename = "emulated")]
    Emulated,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Live
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "postgresql")]
    Postgresql,
    #[serde(rename = "bigquery")]
    Bigquery,
    #[serde(rename = "snowflake")]
    Snowflake,
    #[serde(rename = "redshift")]
    Redshift,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Postgresql
    }
}

