/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigureFreshsalesRequest {
    #[serde(rename = "apiKey")]
    pub api_key: String,
    #[serde(rename = "baseUrl")]
    pub base_url: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
}

impl ConfigureFreshsalesRequest {
    pub fn new(api_key: String, base_url: String, label: String) -> ConfigureFreshsalesRequest {
        ConfigureFreshsalesRequest {
            api_key,
            base_url,
            label,
            mode: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "live")]
    Live,
    #[serde(rename = "emulated")]
    Emulated,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Live
    }
}

