/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigureCrmSyncRequestConfigurationHubspot {
    #[serde(rename = "contactOwnerId", deserialize_with = "Option::deserialize")]
    pub contact_owner_id: Option<String>,
    #[serde(rename = "deal")]
    pub deal: Box<models::ConfigureCrmSyncRequestConfigurationHubspotDeal>,
}

impl ConfigureCrmSyncRequestConfigurationHubspot {
    pub fn new(contact_owner_id: Option<String>, deal: models::ConfigureCrmSyncRequestConfigurationHubspotDeal) -> ConfigureCrmSyncRequestConfigurationHubspot {
        ConfigureCrmSyncRequestConfigurationHubspot {
            contact_owner_id,
            deal: Box::new(deal),
        }
    }
}

