/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigureCodaRequest {
    #[serde(rename = "apiToken")]
    pub api_token: String,
    #[serde(rename = "docId")]
    pub doc_id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "mapping")]
    pub mapping: Box<models::ConfigureCodaRequestMapping>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
    #[serde(rename = "tableId")]
    pub table_id: String,
}

impl ConfigureCodaRequest {
    pub fn new(api_token: String, doc_id: String, label: String, mapping: models::ConfigureCodaRequestMapping, table_id: String) -> ConfigureCodaRequest {
        ConfigureCodaRequest {
            api_token,
            doc_id,
            label,
            mapping: Box::new(mapping),
            mode: None,
            table_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "live")]
    Live,
    #[serde(rename = "emulated")]
    Emulated,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Live
    }
}

