/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigureCrmSyncRequestConfigurationHubspotDeal {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "ownerId", deserialize_with = "Option::deserialize")]
    pub owner_id: Option<String>,
    #[serde(rename = "pipeline", deserialize_with = "Option::deserialize")]
    pub pipeline: Option<String>,
    #[serde(rename = "stage", deserialize_with = "Option::deserialize")]
    pub stage: Option<String>,
}

impl ConfigureCrmSyncRequestConfigurationHubspotDeal {
    pub fn new(enabled: bool, owner_id: Option<String>, pipeline: Option<String>, stage: Option<String>) -> ConfigureCrmSyncRequestConfigurationHubspotDeal {
        ConfigureCrmSyncRequestConfigurationHubspotDeal {
            enabled,
            owner_id,
            pipeline,
            stage,
        }
    }
}

