/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAutomationHookRequest {
    #[serde(rename = "callbackUrl")]
    pub callback_url: String,
    #[serde(rename = "event")]
    pub event: Event,
}

impl CreateAutomationHookRequest {
    pub fn new(callback_url: String, event: Event) -> CreateAutomationHookRequest {
        CreateAutomationHookRequest {
            callback_url,
            event,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "lead.created")]
    LeadCreated,
    #[serde(rename = "lead.verified")]
    LeadVerified,
    #[serde(rename = "integration.job.completed")]
    IntegrationJobCompleted,
    #[serde(rename = "sequence.created")]
    SequenceCreated,
    #[serde(rename = "sequence.email.opened")]
    SequenceEmailOpened,
    #[serde(rename = "sequence.reply.received")]
    SequenceReplyReceived,
}

impl Default for Event {
    fn default() -> Event {
        Self::LeadCreated
    }
}

