/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrmSyncConfigurationResponse {
    #[serde(rename = "configuration")]
    pub configuration: models::CrmSyncConfiguration,
    #[serde(rename = "connection")]
    pub connection: models::IntegrationConnection,
}

impl CrmSyncConfigurationResponse {
    pub fn new(configuration: models::CrmSyncConfiguration, connection: models::IntegrationConnection) -> CrmSyncConfigurationResponse {
        CrmSyncConfigurationResponse {
            configuration,
            connection,
        }
    }
}

