/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrmMappingOptionsResponseOptionsObjectsInner {
    #[serde(rename = "fields")]
    pub fields: Vec<models::CrmRemoteField>,
    /// Known values: Lead, Contact, Person, DataSource. Clients preserve future values.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label")]
    pub label: String,
}

impl CrmMappingOptionsResponseOptionsObjectsInner {
    pub fn new(fields: Vec<models::CrmRemoteField>, id: String, label: String) -> CrmMappingOptionsResponseOptionsObjectsInner {
        CrmMappingOptionsResponseOptionsObjectsInner {
            fields,
            id,
            label,
        }
    }
}

