/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteLeadResponse {
    #[serde(rename = "success")]
    pub success: bool,
}

impl DeleteLeadResponse {
    pub fn new(success: bool) -> DeleteLeadResponse {
        DeleteLeadResponse {
            success,
        }
    }
}

