/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainCompanyContextCompany {
    #[serde(rename = "address", deserialize_with = "Option::deserialize")]
    pub address: Option<models::CompanyContextAddress>,
    #[serde(rename = "companyType", deserialize_with = "Option::deserialize")]
    pub company_type: Option<String>,
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "employeeCount", deserialize_with = "Option::deserialize")]
    pub employee_count: Option<i32>,
    #[serde(rename = "employeeRange", deserialize_with = "Option::deserialize")]
    pub employee_range: Option<String>,
    #[serde(rename = "followerCount", deserialize_with = "Option::deserialize")]
    pub follower_count: Option<i32>,
    #[serde(rename = "foundedOn", deserialize_with = "Option::deserialize")]
    pub founded_on: Option<String>,
    #[serde(rename = "headquarters", deserialize_with = "Option::deserialize")]
    pub headquarters: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "industry", deserialize_with = "Option::deserialize")]
    pub industry: Option<String>,
    #[serde(rename = "jobs")]
    pub jobs: Vec<models::CompanyContextJob>,
    #[serde(rename = "linkedin", deserialize_with = "Option::deserialize")]
    pub linkedin: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "sources")]
    pub sources: Vec<models::CompanyContextSource>,
    #[serde(rename = "specialties")]
    pub specialties: Vec<String>,
    #[serde(rename = "stockSymbol", deserialize_with = "Option::deserialize")]
    pub stock_symbol: Option<String>,
    #[serde(rename = "tagline", deserialize_with = "Option::deserialize")]
    pub tagline: Option<String>,
    #[serde(rename = "website", deserialize_with = "Option::deserialize")]
    pub website: Option<String>,
}

impl DomainCompanyContextCompany {
    pub fn new(address: Option<models::CompanyContextAddress>, company_type: Option<String>, description: Option<String>, domain: String, employee_count: Option<i32>, employee_range: Option<String>, follower_count: Option<i32>, founded_on: Option<String>, headquarters: Option<String>, id: String, industry: Option<String>, jobs: Vec<models::CompanyContextJob>, linkedin: Option<String>, name: String, sources: Vec<models::CompanyContextSource>, specialties: Vec<String>, stock_symbol: Option<String>, tagline: Option<String>, website: Option<String>) -> DomainCompanyContextCompany {
        DomainCompanyContextCompany {
            address,
            company_type,
            description,
            domain,
            employee_count,
            employee_range,
            follower_count,
            founded_on,
            headquarters,
            id,
            industry,
            jobs,
            linkedin,
            name,
            sources,
            specialties,
            stock_symbol,
            tagline,
            website,
        }
    }
}

