/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainCatchAll {
    #[serde(rename = "catch_all", deserialize_with = "Option::deserialize")]
    pub catch_all: Option<bool>,
}

impl DomainCatchAll {
    pub fn new(catch_all: Option<bool>) -> DomainCatchAll {
        DomainCatchAll {
            catch_all,
        }
    }
}

