/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailNotFoundError {
    #[serde(rename = "error")]
    pub error: models::EmailNotFoundErrorError,
}

impl EmailNotFoundError {
    pub fn new(error: models::EmailNotFoundErrorError) -> EmailNotFoundError {
        EmailNotFoundError {
            error,
        }
    }
}

