/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExcelWorkbookInspectionResponse {
    #[serde(rename = "inspection")]
    pub inspection: models::ExcelWorkbookInspectionResponseInspection,
}

impl ExcelWorkbookInspectionResponse {
    pub fn new(inspection: models::ExcelWorkbookInspectionResponseInspection) -> ExcelWorkbookInspectionResponse {
        ExcelWorkbookInspectionResponse {
            inspection,
        }
    }
}

