/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecuteIntegrationCapabilityRequest {
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "input")]
    pub input: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
}

impl ExecuteIntegrationCapabilityRequest {
    pub fn new(idempotency_key: String, input: std::collections::HashMap<String, serde_json::Value>) -> ExecuteIntegrationCapabilityRequest {
        ExecuteIntegrationCapabilityRequest {
            idempotency_key,
            input,
            mode: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "preview")]
    Preview,
    #[serde(rename = "live")]
    Live,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Preview
    }
}

