/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLeadResponseLead {
    #[serde(rename = "company", skip_serializing_if = "Option::is_none")]
    pub company: Option<Box<models::GetLeadResponseLeadCompany>>,
    #[serde(rename = "company_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_id: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "created_by", deserialize_with = "Option::deserialize")]
    pub created_by: Option<String>,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "last_activity_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_activity_at: Option<Option<String>>,
    #[serde(rename = "last_contacted_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_contacted_at: Option<Option<String>>,
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<Box<models::CreateLeadRequestPerson>>,
    #[serde(rename = "sync", skip_serializing_if = "Option::is_none")]
    pub sync: Option<Box<models::GetLeadResponseLeadSync>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "team_id")]
    pub team_id: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "verification", skip_serializing_if = "Option::is_none")]
    pub verification: Option<Box<models::GetLeadResponseLeadVerification>>,
}

impl GetLeadResponseLead {
    pub fn new(created_at: String, created_by: Option<String>, email: String, id: String, team_id: String, updated_at: String) -> GetLeadResponseLead {
        GetLeadResponseLead {
            company: None,
            company_id: None,
            created_at,
            created_by,
            email,
            id,
            last_activity_at: None,
            last_contacted_at: None,
            person: None,
            sync: None,
            tags: None,
            team_id,
            updated_at,
            verification: None,
        }
    }
}

