/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLeadResponseLeadVerification {
    #[serde(rename = "confidence_score", deserialize_with = "Option::deserialize")]
    pub confidence_score: Option<f64>,
    #[serde(rename = "status", deserialize_with = "Option::deserialize")]
    pub status: Option<String>,
}

impl GetLeadResponseLeadVerification {
    pub fn new(confidence_score: Option<f64>, status: Option<String>) -> GetLeadResponseLeadVerification {
        GetLeadResponseLeadVerification {
            confidence_score,
            status,
        }
    }
}

