/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoogleSheetInspectionResponseInspection {
    #[serde(rename = "headers")]
    pub headers: Vec<String>,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "sheetName")]
    pub sheet_name: String,
    #[serde(rename = "sheets")]
    pub sheets: Vec<String>,
    #[serde(rename = "spreadsheetId")]
    pub spreadsheet_id: String,
    #[serde(rename = "title")]
    pub title: String,
}

impl GoogleSheetInspectionResponseInspection {
    pub fn new(headers: Vec<String>, provider: String, sheet_name: String, sheets: Vec<String>, spreadsheet_id: String, title: String) -> GoogleSheetInspectionResponseInspection {
        GoogleSheetInspectionResponseInspection {
            headers,
            provider,
            sheet_name,
            sheets,
            spreadsheet_id,
            title,
        }
    }
}

