/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HubSpotConfigurationOptionsResponseOptionsPipelinesInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "stages")]
    pub stages: Vec<models::HubSpotConfigurationOptionsResponseOptionsPipelinesInnerStagesInner>,
}

impl HubSpotConfigurationOptionsResponseOptionsPipelinesInner {
    pub fn new(id: String, label: String, stages: Vec<models::HubSpotConfigurationOptionsResponseOptionsPipelinesInnerStagesInner>) -> HubSpotConfigurationOptionsResponseOptionsPipelinesInner {
        HubSpotConfigurationOptionsResponseOptionsPipelinesInner {
            id,
            label,
            stages,
        }
    }
}

