/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HubSpotConfigurationOptionsResponseOptions {
    #[serde(rename = "owners")]
    pub owners: Vec<models::HubSpotConfigurationOptionsResponseOptionsOwnersInner>,
    #[serde(rename = "pipelines")]
    pub pipelines: Vec<models::HubSpotConfigurationOptionsResponseOptionsPipelinesInner>,
}

impl HubSpotConfigurationOptionsResponseOptions {
    pub fn new(owners: Vec<models::HubSpotConfigurationOptionsResponseOptionsOwnersInner>, pipelines: Vec<models::HubSpotConfigurationOptionsResponseOptionsPipelinesInner>) -> HubSpotConfigurationOptionsResponseOptions {
        HubSpotConfigurationOptionsResponseOptions {
            owners,
            pipelines,
        }
    }
}

