/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HubSpotConfigurationOptionsResponseOptionsOwnersInner {
    #[serde(rename = "email", deserialize_with = "Option::deserialize")]
    pub email: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label")]
    pub label: String,
}

impl HubSpotConfigurationOptionsResponseOptionsOwnersInner {
    pub fn new(email: Option<String>, id: String, label: String) -> HubSpotConfigurationOptionsResponseOptionsOwnersInner {
        HubSpotConfigurationOptionsResponseOptionsOwnersInner {
            email,
            id,
            label,
        }
    }
}

