/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsightPlatformDetectedEvent {
    #[serde(rename = "email")]
    pub email: String,
    /// Known values: platform_detected. Clients preserve future values.
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "platform")]
    pub platform: String,
}

impl InsightPlatformDetectedEvent {
    pub fn new(email: String, kind: String, platform: String) -> InsightPlatformDetectedEvent {
        InsightPlatformDetectedEvent {
            email,
            kind,
            platform,
        }
    }
}

