/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsightMentionInsightEvent {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "insight")]
    pub insight: models::PersonInsight,
    /// Known values: mention_insight. Clients preserve future values.
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "sourceUrl")]
    pub source_url: String,
}

impl InsightMentionInsightEvent {
    pub fn new(email: String, insight: models::PersonInsight, kind: String, source_url: String) -> InsightMentionInsightEvent {
        InsightMentionInsightEvent {
            email,
            insight,
            kind,
            source_url,
        }
    }
}

