/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsightMentionErrorEvent {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "error")]
    pub error: String,
    /// Known values: mention_error. Clients preserve future values.
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "sourceUrl")]
    pub source_url: String,
}

impl InsightMentionErrorEvent {
    pub fn new(email: String, error: String, kind: String, source_url: String) -> InsightMentionErrorEvent {
        InsightMentionErrorEvent {
            email,
            error,
            kind,
            source_url,
        }
    }
}

