/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsightJurisdiction {
    #[serde(rename = "countryCode", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(rename = "county", skip_serializing_if = "Option::is_none")]
    pub county: Option<String>,
    #[serde(rename = "stateCode", skip_serializing_if = "Option::is_none")]
    pub state_code: Option<String>,
}

impl InsightJurisdiction {
    pub fn new() -> InsightJurisdiction {
        InsightJurisdiction {
            country_code: None,
            county: None,
            state_code: None,
        }
    }
}

