/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsightRole {
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(rename = "endedAt", skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<String>,
    #[serde(rename = "isCurrent", skip_serializing_if = "Option::is_none")]
    pub is_current: Option<bool>,
    #[serde(rename = "seniority", skip_serializing_if = "Option::is_none")]
    pub seniority: Option<String>,
    #[serde(rename = "startedAt", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl InsightRole {
    pub fn new() -> InsightRole {
        InsightRole {
            department: None,
            ended_at: None,
            is_current: None,
            seniority: None,
            started_at: None,
            title: None,
        }
    }
}

