/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsightStartedEvent {
    #[serde(rename = "email")]
    pub email: String,
    /// Known values: started. Clients preserve future values.
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "total")]
    pub total: i32,
}

impl InsightStartedEvent {
    pub fn new(email: String, kind: String, total: i32) -> InsightStartedEvent {
        InsightStartedEvent {
            email,
            kind,
            total,
        }
    }
}

