/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsightMentionExtractedEvent {
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "emailMoved")]
    pub email_moved: bool,
    #[serde(rename = "index")]
    pub index: i32,
    /// Known values: mention_extracted. Clients preserve future values.
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "sourceType")]
    pub source_type: String,
    #[serde(rename = "sourceUrl")]
    pub source_url: String,
    #[serde(rename = "total")]
    pub total: i32,
}

impl InsightMentionExtractedEvent {
    pub fn new(domain: String, email: String, email_moved: bool, index: i32, kind: String, source_type: String, source_url: String, total: i32) -> InsightMentionExtractedEvent {
        InsightMentionExtractedEvent {
            domain,
            email,
            email_moved,
            index,
            kind,
            source_type,
            source_url,
            total,
        }
    }
}

