/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsightAddressEntry {
    #[serde(rename = "address")]
    pub address: models::InsightAddress,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Known values: physical, mailing, billing, shipping, registered, other. Clients preserve future values.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl InsightAddressEntry {
    pub fn new(address: models::InsightAddress, r#type: String) -> InsightAddressEntry {
        InsightAddressEntry {
            address,
            label: None,
            r#type,
        }
    }
}

