/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InspectExcelWorkbookRequest {
    #[serde(rename = "connectionId")]
    pub connection_id: String,
    #[serde(rename = "driveItemId", skip_serializing_if = "Option::is_none")]
    pub drive_item_id: Option<String>,
    #[serde(rename = "shareUrl", skip_serializing_if = "Option::is_none")]
    pub share_url: Option<String>,
    #[serde(rename = "worksheet", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub worksheet: Option<Option<String>>,
}

impl InspectExcelWorkbookRequest {
    pub fn new(connection_id: String) -> InspectExcelWorkbookRequest {
        InspectExcelWorkbookRequest {
            connection_id,
            drive_item_id: None,
            share_url: None,
            worksheet: None,
        }
    }
}

