/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegrationFormConnectionResponse {
    #[serde(rename = "callbackConfigured")]
    pub callback_configured: bool,
    #[serde(rename = "connection")]
    pub connection: models::IntegrationConnection,
}

impl IntegrationFormConnectionResponse {
    pub fn new(callback_configured: bool, connection: models::IntegrationConnection) -> IntegrationFormConnectionResponse {
        IntegrationFormConnectionResponse {
            callback_configured,
            connection,
        }
    }
}

