/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegrationJobPage {
    #[serde(rename = "jobs")]
    pub jobs: Vec<models::IntegrationJob>,
    #[serde(rename = "nextCursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
}

impl IntegrationJobPage {
    pub fn new(jobs: Vec<models::IntegrationJob>, next_cursor: Option<String>) -> IntegrationJobPage {
        IntegrationJobPage {
            jobs,
            next_cursor,
        }
    }
}

