/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegrationConnectionHealth {
    #[serde(rename = "checked_at", deserialize_with = "Option::deserialize")]
    pub checked_at: Option<String>,
    #[serde(rename = "code", deserialize_with = "Option::deserialize")]
    pub code: Option<String>,
    #[serde(rename = "last_error_code", deserialize_with = "Option::deserialize")]
    pub last_error_code: Option<String>,
    #[serde(rename = "last_error_message", deserialize_with = "Option::deserialize")]
    pub last_error_message: Option<String>,
    /// Known values: unknown, healthy, degraded, down. Clients preserve future values.
    #[serde(rename = "state")]
    pub state: String,
}

impl IntegrationConnectionHealth {
    pub fn new(checked_at: Option<String>, code: Option<String>, last_error_code: Option<String>, last_error_message: Option<String>, state: String) -> IntegrationConnectionHealth {
        IntegrationConnectionHealth {
            checked_at,
            code,
            last_error_code,
            last_error_message,
            state,
        }
    }
}

