/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegrationConnectionTestResponse {
    #[serde(rename = "connection")]
    pub connection: models::IntegrationConnection,
    #[serde(rename = "test")]
    pub test: models::IntegrationConnectionTest,
}

impl IntegrationConnectionTestResponse {
    pub fn new(connection: models::IntegrationConnection, test: models::IntegrationConnectionTest) -> IntegrationConnectionTestResponse {
        IntegrationConnectionTestResponse {
            connection,
            test,
        }
    }
}

