/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegrationJobCounters {
    #[serde(rename = "failed")]
    pub failed: i32,
    #[serde(rename = "processed")]
    pub processed: i32,
    #[serde(rename = "skipped")]
    pub skipped: i32,
    #[serde(rename = "succeeded")]
    pub succeeded: i32,
}

impl IntegrationJobCounters {
    pub fn new(failed: i32, processed: i32, skipped: i32, succeeded: i32) -> IntegrationJobCounters {
        IntegrationJobCounters {
            failed,
            processed,
            skipped,
            succeeded,
        }
    }
}

