/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeadExportInnerCompany {
    #[serde(rename = "location", deserialize_with = "Option::deserialize")]
    pub location: Option<String>,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "website", deserialize_with = "Option::deserialize")]
    pub website: Option<String>,
}

impl LeadExportInnerCompany {
    pub fn new(location: Option<String>, name: Option<String>, website: Option<String>) -> LeadExportInnerCompany {
        LeadExportInnerCompany {
            location,
            name,
            website,
        }
    }
}

