/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeadPage {
    #[serde(rename = "groupTotals", deserialize_with = "Option::deserialize")]
    pub group_totals: Option<std::collections::HashMap<String, i32>>,
    #[serde(rename = "lastGroupCursor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_group_cursor: Option<Option<String>>,
    #[serde(rename = "nextCursor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<Option<String>>,
    #[serde(rename = "nextGroupCursor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_group_cursor: Option<Option<String>>,
    #[serde(rename = "results")]
    pub results: Vec<models::LeadPageResultsInner>,
    #[serde(rename = "totalCount")]
    pub total_count: i32,
}

impl LeadPage {
    pub fn new(group_totals: Option<std::collections::HashMap<String, i32>>, results: Vec<models::LeadPageResultsInner>, total_count: i32) -> LeadPage {
        LeadPage {
            group_totals,
            last_group_cursor: None,
            next_cursor: None,
            next_group_cursor: None,
            results,
            total_count,
        }
    }
}

