/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailDomainHealthCheck {
    #[serde(rename = "evidence")]
    pub evidence: Vec<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "summary")]
    pub summary: String,
}

impl MailDomainHealthCheck {
    pub fn new(evidence: Vec<String>, name: String, status: String, summary: String) -> MailDomainHealthCheck {
        MailDomainHealthCheck {
            evidence,
            name,
            status,
            summary,
        }
    }
}

