/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostTemplatesRequest {
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "channel")]
    pub channel: Channel,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "whatsappApproval", skip_serializing_if = "Option::is_none")]
    pub whatsapp_approval: Option<Box<models::MailPostTemplatesRequestWhatsappApproval>>,
}

impl MailPostTemplatesRequest {
    pub fn new(body: String, channel: Channel, name: String, status: Status) -> MailPostTemplatesRequest {
        MailPostTemplatesRequest {
            body,
            channel,
            id: None,
            name,
            status,
            subject: None,
            whatsapp_approval: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Channel {
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "sms")]
    Sms,
    #[serde(rename = "whatsapp")]
    Whatsapp,
}

impl Default for Channel {
    fn default() -> Channel {
        Self::Email
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "published")]
    Published,
    #[serde(rename = "archived")]
    Archived,
}

impl Default for Status {
    fn default() -> Status {
        Self::Draft
    }
}

