/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailCampaignDraftRecord {
    #[serde(rename = "audienceListIds")]
    pub audience_list_ids: Vec<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "launchedAt", skip_serializing_if = "Option::is_none")]
    pub launched_at: Option<String>,
    #[serde(rename = "mailboxIds")]
    pub mailbox_ids: Vec<String>,
    #[serde(rename = "mailboxPoolId", skip_serializing_if = "Option::is_none")]
    pub mailbox_pool_id: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "policy")]
    pub policy: Box<models::MailMessagePolicyInput>,
    #[serde(rename = "scheduledAt", skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "steps")]
    pub steps: Vec<models::MailCampaignDraftStep>,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "version")]
    pub version: f64,
}

impl MailCampaignDraftRecord {
    pub fn new(audience_list_ids: Vec<String>, created_at: String, id: String, mailbox_ids: Vec<String>, name: String, policy: models::MailMessagePolicyInput, status: String, steps: Vec<models::MailCampaignDraftStep>, tenant_id: String, updated_at: String, version: f64) -> MailCampaignDraftRecord {
        MailCampaignDraftRecord {
            audience_list_ids,
            created_at,
            id,
            launched_at: None,
            mailbox_ids,
            mailbox_pool_id: None,
            name,
            policy: Box::new(policy),
            scheduled_at: None,
            status,
            steps,
            tenant_id,
            updated_at,
            version,
        }
    }
}

