/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailDeleteCampaignsByCampaignIdRequest {
    #[serde(rename = "expectedVersion")]
    pub expected_version: i32,
}

impl MailDeleteCampaignsByCampaignIdRequest {
    pub fn new(expected_version: i32) -> MailDeleteCampaignsByCampaignIdRequest {
        MailDeleteCampaignsByCampaignIdRequest {
            expected_version,
        }
    }
}

