/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostMailboxesManualRequestSmtp {
    #[serde(rename = "host")]
    pub host: String,
    #[serde(rename = "messageIdDomain", skip_serializing_if = "Option::is_none")]
    pub message_id_domain: Option<String>,
    #[serde(rename = "password")]
    pub password: String,
    /// Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "security")]
    pub security: Security,
    #[serde(rename = "serverName", skip_serializing_if = "Option::is_none")]
    pub server_name: Option<String>,
    #[serde(rename = "tlsCa", skip_serializing_if = "Option::is_none")]
    pub tls_ca: Option<String>,
    #[serde(rename = "username")]
    pub username: String,
}

impl MailPostMailboxesManualRequestSmtp {
    pub fn new(host: String, password: String, port: i32, security: Security, username: String) -> MailPostMailboxesManualRequestSmtp {
        MailPostMailboxesManualRequestSmtp {
            host,
            message_id_domain: None,
            password,
            port,
            security,
            server_name: None,
            tls_ca: None,
            username,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Security {
    #[serde(rename = "tls")]
    Tls,
    #[serde(rename = "starttls")]
    Starttls,
    #[serde(rename = "plain")]
    Plain,
}

impl Default for Security {
    fn default() -> Security {
        Self::Tls
    }
}

