/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailCadenceNodeAnyOf1 {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "experiment", skip_serializing_if = "Option::is_none")]
    pub experiment: Option<Box<models::MailCadenceMessageExperiment>>,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "nextNodeId")]
    pub next_node_id: String,
    #[serde(rename = "templateId")]
    pub template_id: String,
    #[serde(rename = "templateVersion")]
    pub template_version: f64,
}

impl MailCadenceNodeAnyOf1 {
    pub fn new(id: String, name: String, channel: String, kind: Kind, next_node_id: String, template_id: String, template_version: f64) -> MailCadenceNodeAnyOf1 {
        MailCadenceNodeAnyOf1 {
            id,
            name,
            channel,
            experiment: None,
            kind,
            next_node_id,
            template_id,
            template_version,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "message")]
    Message,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Message
    }
}

