/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailMailboxPoolMember {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "mailboxId")]
    pub mailbox_id: String,
    #[serde(rename = "poolId")]
    pub pool_id: String,
    #[serde(rename = "priority")]
    pub priority: f64,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "weight")]
    pub weight: f64,
}

impl MailMailboxPoolMember {
    pub fn new(created_at: String, enabled: bool, mailbox_id: String, pool_id: String, priority: f64, tenant_id: String, updated_at: String, weight: f64) -> MailMailboxPoolMember {
        MailMailboxPoolMember {
            created_at,
            enabled,
            mailbox_id,
            pool_id,
            priority,
            tenant_id,
            updated_at,
            weight,
        }
    }
}

