/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPhoneNumberValue {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "normalized")]
    pub normalized: String,
    #[serde(rename = "raw")]
    pub raw: String,
}

impl MailPhoneNumberValue {
    pub fn new(normalized: String, raw: String) -> MailPhoneNumberValue {
        MailPhoneNumberValue {
            label: None,
            normalized,
            raw,
        }
    }
}

