/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MailPostCadenceRunsRequest : Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCadenceRunsRequest {
    #[serde(rename = "audienceListId", skip_serializing_if = "Option::is_none")]
    pub audience_list_id: Option<String>,
    #[serde(rename = "cadenceId")]
    pub cadence_id: String,
    #[serde(rename = "cadenceVersion", skip_serializing_if = "Option::is_none")]
    pub cadence_version: Option<i32>,
    #[serde(rename = "campaignId", skip_serializing_if = "Option::is_none")]
    pub campaign_id: Option<String>,
    #[serde(rename = "campaignName", skip_serializing_if = "Option::is_none")]
    pub campaign_name: Option<String>,
    #[serde(rename = "contactIds", skip_serializing_if = "Option::is_none")]
    pub contact_ids: Option<Vec<String>>,
    #[serde(rename = "enrollmentMode", skip_serializing_if = "Option::is_none")]
    pub enrollment_mode: Option<EnrollmentMode>,
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "mailboxId", skip_serializing_if = "Option::is_none")]
    pub mailbox_id: Option<String>,
    #[serde(rename = "mailboxPoolId", skip_serializing_if = "Option::is_none")]
    pub mailbox_pool_id: Option<String>,
    #[serde(rename = "scheduledAt", skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
}

impl MailPostCadenceRunsRequest {
    /// Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
    pub fn new(cadence_id: String, idempotency_key: String) -> MailPostCadenceRunsRequest {
        MailPostCadenceRunsRequest {
            audience_list_id: None,
            cadence_id,
            cadence_version: None,
            campaign_id: None,
            campaign_name: None,
            contact_ids: None,
            enrollment_mode: None,
            idempotency_key,
            mailbox_id: None,
            mailbox_pool_id: None,
            scheduled_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnrollmentMode {
    #[serde(rename = "new_only")]
    NewOnly,
    #[serde(rename = "reenroll")]
    Reenroll,
}

impl Default for EnrollmentMode {
    fn default() -> EnrollmentMode {
        Self::NewOnly
    }
}

