/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCrmContactsBatchResponse200 {
    #[serde(rename = "results")]
    pub results: Vec<models::MailContactRecord>,
}

impl MailPostCrmContactsBatchResponse200 {
    pub fn new(results: Vec<models::MailContactRecord>) -> MailPostCrmContactsBatchResponse200 {
        MailPostCrmContactsBatchResponse200 {
            results,
        }
    }
}

