/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetMessagesResponse200 {
    #[serde(rename = "messages")]
    pub messages: Vec<models::MailMessageRecord>,
    #[serde(rename = "nextCursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

impl MailGetMessagesResponse200 {
    pub fn new(messages: Vec<models::MailMessageRecord>) -> MailGetMessagesResponse200 {
        MailGetMessagesResponse200 {
            messages,
            next_cursor: None,
        }
    }
}

