/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner {
    #[serde(rename = "maxAccepted")]
    pub max_accepted: i32,
    #[serde(rename = "windowMs")]
    pub window_ms: i32,
}

impl MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner {
    pub fn new(max_accepted: i32, window_ms: i32) -> MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner {
        MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner {
            max_accepted,
            window_ms,
        }
    }
}

