/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostAnalyticsExportRequest {
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<Box<models::MailPostAnalyticsExportRequestAfter>>,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "to")]
    pub to: String,
}

impl MailPostAnalyticsExportRequest {
    pub fn new(from: String, to: String) -> MailPostAnalyticsExportRequest {
        MailPostAnalyticsExportRequest {
            after: None,
            from,
            limit: None,
            to,
        }
    }
}

