/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCrmTasksRequest {
    #[serde(rename = "assignedToActorId")]
    pub assigned_to_actor_id: String,
    #[serde(rename = "contactId")]
    pub contact_id: String,
    #[serde(rename = "dueAt")]
    pub due_at: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MailPostCrmTasksRequest {
    pub fn new(assigned_to_actor_id: String, contact_id: String, due_at: String, title: String, r#type: Type) -> MailPostCrmTasksRequest {
        MailPostCrmTasksRequest {
            assigned_to_actor_id,
            contact_id,
            due_at,
            title,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "call")]
    Call,
    #[serde(rename = "manual_email")]
    ManualEmail,
    #[serde(rename = "linkedin_profile_visit")]
    LinkedinProfileVisit,
    #[serde(rename = "linkedin_follow")]
    LinkedinFollow,
    #[serde(rename = "linkedin_connection")]
    LinkedinConnection,
    #[serde(rename = "linkedin_message")]
    LinkedinMessage,
    #[serde(rename = "linkedin_voice")]
    LinkedinVoice,
    #[serde(rename = "research")]
    Research,
    #[serde(rename = "personalization")]
    Personalization,
    #[serde(rename = "review")]
    Review,
    #[serde(rename = "follow_up")]
    FollowUp,
    #[serde(rename = "other")]
    Other,
}

impl Default for Type {
    fn default() -> Type {
        Self::Call
    }
}

