/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailCadenceEnrollmentVariableGap {
    #[serde(rename = "contactCount")]
    pub contact_count: f64,
    #[serde(rename = "variable")]
    pub variable: String,
}

impl MailCadenceEnrollmentVariableGap {
    pub fn new(contact_count: f64, variable: String) -> MailCadenceEnrollmentVariableGap {
        MailCadenceEnrollmentVariableGap {
            contact_count,
            variable,
        }
    }
}

