/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostReplyAutomationsRequest {
    #[serde(rename = "actions")]
    pub actions: Box<models::MailPostReplyAutomationsRequestActions>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "labels")]
    pub labels: Vec<Labels>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
}

impl MailPostReplyAutomationsRequest {
    pub fn new(actions: models::MailPostReplyAutomationsRequestActions, labels: Vec<Labels>, name: String) -> MailPostReplyAutomationsRequest {
        MailPostReplyAutomationsRequest {
            actions: Box::new(actions),
            enabled: None,
            id: None,
            labels,
            name,
            priority: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Labels {
    #[serde(rename = "interested")]
    Interested,
    #[serde(rename = "not_interested")]
    NotInterested,
    #[serde(rename = "out_of_office")]
    OutOfOffice,
    #[serde(rename = "wrong_person")]
    WrongPerson,
    #[serde(rename = "meeting_booked")]
    MeetingBooked,
    #[serde(rename = "unsubscribe")]
    Unsubscribe,
    #[serde(rename = "bounce")]
    Bounce,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Labels {
    fn default() -> Labels {
        Self::Interested
    }
}

