/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostTemplatesResponse200 {
    #[serde(rename = "template")]
    pub template: Box<models::MailMessageTemplateVersion>,
}

impl MailPostTemplatesResponse200 {
    pub fn new(template: models::MailMessageTemplateVersion) -> MailPostTemplatesResponse200 {
        MailPostTemplatesResponse200 {
            template: Box::new(template),
        }
    }
}

