/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPatchWebhooksBySubscriptionIdResponse200 {
    #[serde(rename = "subscription")]
    pub subscription: Box<models::MailGetWebhooksResponse200SubscriptionsInner>,
}

impl MailPatchWebhooksBySubscriptionIdResponse200 {
    pub fn new(subscription: models::MailGetWebhooksResponse200SubscriptionsInner) -> MailPatchWebhooksBySubscriptionIdResponse200 {
        MailPatchWebhooksBySubscriptionIdResponse200 {
            subscription: Box::new(subscription),
        }
    }
}

