/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCadencesByCadenceIdCopyRequest {
    #[serde(rename = "targetName")]
    pub target_name: String,
    #[serde(rename = "targetTeamId")]
    pub target_team_id: String,
}

impl MailPostCadencesByCadenceIdCopyRequest {
    pub fn new(target_name: String, target_team_id: String) -> MailPostCadencesByCadenceIdCopyRequest {
        MailPostCadencesByCadenceIdCopyRequest {
            target_name,
            target_team_id,
        }
    }
}

