/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostTrackingDomainResponse200 {
    #[serde(rename = "domain")]
    pub domain: Box<models::MailTrackingDomainRecord>,
}

impl MailPostTrackingDomainResponse200 {
    pub fn new(domain: models::MailTrackingDomainRecord) -> MailPostTrackingDomainResponse200 {
        MailPostTrackingDomainResponse200 {
            domain: Box::new(domain),
        }
    }
}

