/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetChannelsResponse200Whatsapp {
    #[serde(rename = "approvedTemplateRequired")]
    pub approved_template_required: bool,
    #[serde(rename = "configured")]
    pub configured: bool,
    #[serde(rename = "consentRequired")]
    pub consent_required: bool,
    #[serde(rename = "costCeilingRequired")]
    pub cost_ceiling_required: bool,
    #[serde(rename = "executionEnabled")]
    pub execution_enabled: bool,
    #[serde(rename = "sequenceSupported")]
    pub sequence_supported: bool,
}

impl MailGetChannelsResponse200Whatsapp {
    pub fn new(approved_template_required: bool, configured: bool, consent_required: bool, cost_ceiling_required: bool, execution_enabled: bool, sequence_supported: bool) -> MailGetChannelsResponse200Whatsapp {
        MailGetChannelsResponse200Whatsapp {
            approved_template_required,
            configured,
            consent_required,
            cost_ceiling_required,
            execution_enabled,
            sequence_supported,
        }
    }
}

