/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailDeleteCampaignsByCampaignIdResponse200 {
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl MailDeleteCampaignsByCampaignIdResponse200 {
    pub fn new(deleted: bool) -> MailDeleteCampaignsByCampaignIdResponse200 {
        MailDeleteCampaignsByCampaignIdResponse200 {
            deleted,
        }
    }
}

