/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCrmTasksByTaskIdCompleteResponse200 {
    #[serde(rename = "resumedCadenceRunIds")]
    pub resumed_cadence_run_ids: Vec<String>,
    #[serde(rename = "task")]
    pub task: Box<models::MailCrmTask>,
}

impl MailPostCrmTasksByTaskIdCompleteResponse200 {
    pub fn new(resumed_cadence_run_ids: Vec<String>, task: models::MailCrmTask) -> MailPostCrmTasksByTaskIdCompleteResponse200 {
        MailPostCrmTasksByTaskIdCompleteResponse200 {
            resumed_cadence_run_ids,
            task: Box::new(task),
        }
    }
}

