/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCrmNotesResponse200Event {
    #[serde(rename = "actorId")]
    pub actor_id: String,
    #[serde(rename = "contactId")]
    pub contact_id: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "occurredAt")]
    pub occurred_at: String,
    #[serde(rename = "payload")]
    pub payload: Box<models::MailPostCrmNotesResponse200EventPayload>,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl MailPostCrmNotesResponse200Event {
    pub fn new(actor_id: String, contact_id: String, id: String, occurred_at: String, payload: models::MailPostCrmNotesResponse200EventPayload, tenant_id: String, r#type: String) -> MailPostCrmNotesResponse200Event {
        MailPostCrmNotesResponse200Event {
            actor_id,
            contact_id,
            id,
            occurred_at,
            payload: Box::new(payload),
            tenant_id,
            r#type,
        }
    }
}

