/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailQuotaRule {
    #[serde(rename = "maxAccepted")]
    pub max_accepted: f64,
    #[serde(rename = "windowMs")]
    pub window_ms: f64,
}

impl MailQuotaRule {
    pub fn new(max_accepted: f64, window_ms: f64) -> MailQuotaRule {
        MailQuotaRule {
            max_accepted,
            window_ms,
        }
    }
}

