/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdRequest {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
}

impl MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdRequest {
    pub fn new() -> MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdRequest {
        MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdRequest {
            enabled: None,
            priority: None,
            weight: None,
        }
    }
}

