/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostSuppressionsRequestAnyOf {
    #[serde(rename = "scope")]
    pub scope: Scope,
    #[serde(rename = "value")]
    pub value: String,
}

impl MailPostSuppressionsRequestAnyOf {
    pub fn new(scope: Scope, value: String) -> MailPostSuppressionsRequestAnyOf {
        MailPostSuppressionsRequestAnyOf {
            scope,
            value,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scope {
    #[serde(rename = "email")]
    Email,
}

impl Default for Scope {
    fn default() -> Scope {
        Self::Email
    }
}

