/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailOperationalAnalyticsOverview {
    #[serde(rename = "cadenceSteps")]
    pub cadence_steps: Vec<models::MailOperationalAnalyticsOverviewCadenceStepsInner>,
    #[serde(rename = "replyLabels")]
    pub reply_labels: std::collections::HashMap<String, f64>,
    #[serde(rename = "sampleLimited")]
    pub sample_limited: bool,
    #[serde(rename = "stages")]
    pub stages: std::collections::HashMap<String, f64>,
    #[serde(rename = "taskOutcomes")]
    pub task_outcomes: std::collections::HashMap<String, f64>,
}

impl MailOperationalAnalyticsOverview {
    pub fn new(cadence_steps: Vec<models::MailOperationalAnalyticsOverviewCadenceStepsInner>, reply_labels: std::collections::HashMap<String, f64>, sample_limited: bool, stages: std::collections::HashMap<String, f64>, task_outcomes: std::collections::HashMap<String, f64>) -> MailOperationalAnalyticsOverview {
        MailOperationalAnalyticsOverview {
            cadence_steps,
            reply_labels,
            sample_limited,
            stages,
            task_outcomes,
        }
    }
}

