/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 {
    #[serde(rename = "member")]
    pub member: Box<models::MailMailboxPoolMember>,
}

impl MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 {
    pub fn new(member: models::MailMailboxPoolMember) -> MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 {
        MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 {
            member: Box::new(member),
        }
    }
}

