/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostMessagesRequest {
    #[serde(rename = "delayMs", skip_serializing_if = "Option::is_none")]
    pub delay_ms: Option<i32>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "mailboxId")]
    pub mailbox_id: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "to")]
    pub to: Box<models::MailPostMessagesRequestTo>,
}

impl MailPostMessagesRequest {
    pub fn new(idempotency_key: String, mailbox_id: String, subject: String, text: String, to: models::MailPostMessagesRequestTo) -> MailPostMessagesRequest {
        MailPostMessagesRequest {
            delay_ms: None,
            html: None,
            idempotency_key,
            mailbox_id,
            subject,
            text,
            to: Box::new(to),
        }
    }
}

