/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCadenceCampaignsResponse202 {
    #[serde(rename = "campaign")]
    pub campaign: Box<models::MailCadenceCampaignRecord>,
}

impl MailPostCadenceCampaignsResponse202 {
    pub fn new(campaign: models::MailCadenceCampaignRecord) -> MailPostCadenceCampaignsResponse202 {
        MailPostCadenceCampaignsResponse202 {
            campaign: Box::new(campaign),
        }
    }
}

