/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostTemplatesRequestWhatsappApproval {
    #[serde(rename = "approvedAt")]
    pub approved_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "language")]
    pub language: String,
    #[serde(rename = "templateName")]
    pub template_name: String,
}

impl MailPostTemplatesRequestWhatsappApproval {
    pub fn new(approved_at: String, id: String, language: String, template_name: String) -> MailPostTemplatesRequestWhatsappApproval {
        MailPostTemplatesRequestWhatsappApproval {
            approved_at,
            id,
            language,
            template_name,
        }
    }
}

