/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailConversationEntryLastErrorAnyOf2 {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "outcome")]
    pub outcome: Outcome,
}

impl MailConversationEntryLastErrorAnyOf2 {
    pub fn new(code: String, message: String, outcome: Outcome) -> MailConversationEntryLastErrorAnyOf2 {
        MailConversationEntryLastErrorAnyOf2 {
            code,
            message,
            outcome,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Outcome {
    #[serde(rename = "unknown_outcome")]
    UnknownOutcome,
}

impl Default for Outcome {
    fn default() -> Outcome {
        Self::UnknownOutcome
    }
}

