/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetAnalyticsResponse200 {
    #[serde(rename = "messages")]
    pub messages: Box<models::MailMessageAnalyticsOverview>,
    #[serde(rename = "operational")]
    pub operational: Box<models::MailOperationalAnalyticsOverview>,
}

impl MailGetAnalyticsResponse200 {
    pub fn new(messages: models::MailMessageAnalyticsOverview, operational: models::MailOperationalAnalyticsOverview) -> MailGetAnalyticsResponse200 {
        MailGetAnalyticsResponse200 {
            messages: Box::new(messages),
            operational: Box::new(operational),
        }
    }
}

