/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetPortfolioResponse200AnyOf {
    #[serde(rename = "portfolio", deserialize_with = "Option::deserialize")]
    pub portfolio: Option<serde_json::Value>,
    #[serde(rename = "suppressions")]
    pub suppressions: Vec<serde_json::Value>,
    #[serde(rename = "teams")]
    pub teams: Vec<serde_json::Value>,
}

impl MailGetPortfolioResponse200AnyOf {
    pub fn new(portfolio: Option<serde_json::Value>, suppressions: Vec<serde_json::Value>, teams: Vec<serde_json::Value>) -> MailGetPortfolioResponse200AnyOf {
        MailGetPortfolioResponse200AnyOf {
            portfolio,
            suppressions,
            teams,
        }
    }
}

