/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCrmNotesResponse200 {
    #[serde(rename = "event")]
    pub event: Box<models::MailPostCrmNotesResponse200Event>,
}

impl MailPostCrmNotesResponse200 {
    pub fn new(event: models::MailPostCrmNotesResponse200Event) -> MailPostCrmNotesResponse200 {
        MailPostCrmNotesResponse200 {
            event: Box::new(event),
        }
    }
}

