/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailSignatureCandidateFields {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::MailEvidenceField>>,
    #[serde(rename = "company", skip_serializing_if = "Option::is_none")]
    pub company: Option<Box<models::MailEvidenceField>>,
    #[serde(rename = "emails")]
    pub emails: Vec<models::MailEvidenceField>,
    #[serde(rename = "jobTitle", skip_serializing_if = "Option::is_none")]
    pub job_title: Option<Box<models::MailEvidenceField>>,
    #[serde(rename = "personName", skip_serializing_if = "Option::is_none")]
    pub person_name: Option<Box<models::MailEvidenceField>>,
    #[serde(rename = "phones")]
    pub phones: Vec<models::MailSignatureCandidateFieldsPhonesInner>,
    #[serde(rename = "socialProfiles")]
    pub social_profiles: Vec<models::MailEvidenceField>,
    #[serde(rename = "websites")]
    pub websites: Vec<models::MailEvidenceField>,
}

impl MailSignatureCandidateFields {
    pub fn new(emails: Vec<models::MailEvidenceField>, phones: Vec<models::MailSignatureCandidateFieldsPhonesInner>, social_profiles: Vec<models::MailEvidenceField>, websites: Vec<models::MailEvidenceField>) -> MailSignatureCandidateFields {
        MailSignatureCandidateFields {
            address: None,
            company: None,
            emails,
            job_title: None,
            person_name: None,
            phones,
            social_profiles,
            websites,
        }
    }
}

