/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCampaignsByCampaignIdStateResponse200 {
    #[serde(rename = "campaign")]
    pub campaign: Box<models::MailCampaignProgress>,
}

impl MailPostCampaignsByCampaignIdStateResponse200 {
    pub fn new(campaign: models::MailCampaignProgress) -> MailPostCampaignsByCampaignIdStateResponse200 {
        MailPostCampaignsByCampaignIdStateResponse200 {
            campaign: Box::new(campaign),
        }
    }
}

