/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCrmNotesRequest {
    #[serde(rename = "contactId")]
    pub contact_id: String,
    #[serde(rename = "text")]
    pub text: String,
}

impl MailPostCrmNotesRequest {
    pub fn new(contact_id: String, text: String) -> MailPostCrmNotesRequest {
        MailPostCrmNotesRequest {
            contact_id,
            text,
        }
    }
}

