/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostDeliverabilityDomainHealthRequest {
    #[serde(rename = "dkimSelectors", skip_serializing_if = "Option::is_none")]
    pub dkim_selectors: Option<Vec<String>>,
    #[serde(rename = "domain")]
    pub domain: String,
}

impl MailPostDeliverabilityDomainHealthRequest {
    pub fn new(domain: String) -> MailPostDeliverabilityDomainHealthRequest {
        MailPostDeliverabilityDomainHealthRequest {
            dkim_selectors: None,
            domain,
        }
    }
}

