/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailDomainHealthReport {
    #[serde(rename = "checkedAt")]
    pub checked_at: String,
    #[serde(rename = "checks")]
    pub checks: Vec<models::MailDomainHealthCheck>,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl MailDomainHealthReport {
    pub fn new(checked_at: String, checks: Vec<models::MailDomainHealthCheck>, domain: String, status: String) -> MailDomainHealthReport {
        MailDomainHealthReport {
            checked_at,
            checks,
            domain,
            status,
        }
    }
}

