/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostDeliverabilityMailboxesByMailboxIdResponse200 {
    #[serde(rename = "health")]
    pub health: Box<models::MailMailboxHealthRecord>,
}

impl MailPostDeliverabilityMailboxesByMailboxIdResponse200 {
    pub fn new(health: models::MailMailboxHealthRecord) -> MailPostDeliverabilityMailboxesByMailboxIdResponse200 {
        MailPostDeliverabilityMailboxesByMailboxIdResponse200 {
            health: Box::new(health),
        }
    }
}

