/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPutCrmStatesResponse200 {
    #[serde(rename = "state")]
    pub state: Box<models::MailContactCrmState>,
}

impl MailPutCrmStatesResponse200 {
    pub fn new(state: models::MailContactCrmState) -> MailPutCrmStatesResponse200 {
        MailPutCrmStatesResponse200 {
            state: Box::new(state),
        }
    }
}

