/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCampaignsByCampaignIdLaunchResponse200AnyOf {
    #[serde(rename = "campaign")]
    pub campaign: Box<models::MailPostCampaignsByCampaignIdLaunchResponse200Campaign>,
    #[serde(rename = "draft")]
    pub draft: Box<models::MailCampaignDraftRecord>,
    #[serde(rename = "sequences")]
    pub sequences: Vec<serde_json::Value>,
}

impl MailPostCampaignsByCampaignIdLaunchResponse200AnyOf {
    pub fn new(campaign: models::MailPostCampaignsByCampaignIdLaunchResponse200Campaign, draft: models::MailCampaignDraftRecord, sequences: Vec<serde_json::Value>) -> MailPostCampaignsByCampaignIdLaunchResponse200AnyOf {
        MailPostCampaignsByCampaignIdLaunchResponse200AnyOf {
            campaign: Box::new(campaign),
            draft: Box::new(draft),
            sequences,
        }
    }
}

