/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostDeliverabilityPoolsResponse201 {
    #[serde(rename = "pool")]
    pub pool: Box<models::MailPostDeliverabilityPoolsResponse201Pool>,
}

impl MailPostDeliverabilityPoolsResponse201 {
    pub fn new(pool: models::MailPostDeliverabilityPoolsResponse201Pool) -> MailPostDeliverabilityPoolsResponse201 {
        MailPostDeliverabilityPoolsResponse201 {
            pool: Box::new(pool),
        }
    }
}

