/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCadenceCampaignsByCampaignIdStateResponse200 {
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "campaignId")]
    pub campaign_id: String,
    #[serde(rename = "changedRuns")]
    pub changed_runs: Vec<models::MailCadenceRunRecord>,
    #[serde(rename = "eligibleRuns")]
    pub eligible_runs: f64,
    #[serde(rename = "totalRuns")]
    pub total_runs: f64,
    #[serde(rename = "campaign")]
    pub campaign: Box<models::MailCadenceCampaignRecord>,
}

impl MailPostCadenceCampaignsByCampaignIdStateResponse200 {
    pub fn new(action: String, campaign_id: String, changed_runs: Vec<models::MailCadenceRunRecord>, eligible_runs: f64, total_runs: f64, campaign: models::MailCadenceCampaignRecord) -> MailPostCadenceCampaignsByCampaignIdStateResponse200 {
        MailPostCadenceCampaignsByCampaignIdStateResponse200 {
            action,
            campaign_id,
            changed_runs,
            eligible_runs,
            total_runs,
            campaign: Box::new(campaign),
        }
    }
}

