/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailMessageAnalyticsOverviewDailyInner {
    #[serde(rename = "accepted")]
    pub accepted: f64,
    #[serde(rename = "bounced")]
    pub bounced: f64,
    #[serde(rename = "complained")]
    pub complained: f64,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "delivered")]
    pub delivered: f64,
    #[serde(rename = "replied")]
    pub replied: f64,
    #[serde(rename = "total")]
    pub total: f64,
}

impl MailMessageAnalyticsOverviewDailyInner {
    pub fn new(accepted: f64, bounced: f64, complained: f64, date: String, delivered: f64, replied: f64, total: f64) -> MailMessageAnalyticsOverviewDailyInner {
        MailMessageAnalyticsOverviewDailyInner {
            accepted,
            bounced,
            complained,
            date,
            delivered,
            replied,
            total,
        }
    }
}

