/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetWebhooksResponse200SubscriptionsInner {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "cursor")]
    pub cursor: f64,
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    #[serde(rename = "eventTypes")]
    pub event_types: Vec<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "version")]
    pub version: f64,
}

impl MailGetWebhooksResponse200SubscriptionsInner {
    pub fn new(created_at: String, cursor: f64, endpoint: String, event_types: Vec<String>, id: String, status: String, tenant_id: String, updated_at: String, version: f64) -> MailGetWebhooksResponse200SubscriptionsInner {
        MailGetWebhooksResponse200SubscriptionsInner {
            created_at,
            cursor,
            endpoint,
            event_types,
            id,
            status,
            tenant_id,
            updated_at,
            version,
        }
    }
}

