/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailCrmTask {
    #[serde(rename = "assignedToActorId")]
    pub assigned_to_actor_id: String,
    #[serde(rename = "completedAt", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<String>,
    #[serde(rename = "contactId")]
    pub contact_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "dueAt")]
    pub due_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "outcome", skip_serializing_if = "Option::is_none")]
    pub outcome: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl MailCrmTask {
    pub fn new(assigned_to_actor_id: String, contact_id: String, created_at: String, due_at: String, id: String, status: String, tenant_id: String, title: String, r#type: String, updated_at: String) -> MailCrmTask {
        MailCrmTask {
            assigned_to_actor_id,
            completed_at: None,
            contact_id,
            created_at,
            due_at,
            id,
            outcome: None,
            status,
            tenant_id,
            title,
            r#type,
            updated_at,
        }
    }
}

