/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetPortfolioResponse200 {
    #[serde(rename = "portfolio")]
    pub portfolio: Box<models::MailMailPortfolio>,
    #[serde(rename = "suppressions")]
    pub suppressions: Vec<models::MailMailPortfolioSuppression>,
    #[serde(rename = "teams")]
    pub teams: Vec<models::MailMailPortfolioTeam>,
}

impl MailGetPortfolioResponse200 {
    pub fn new(portfolio: models::MailMailPortfolio, suppressions: Vec<models::MailMailPortfolioSuppression>, teams: Vec<models::MailMailPortfolioTeam>) -> MailGetPortfolioResponse200 {
        MailGetPortfolioResponse200 {
            portfolio: Box::new(portfolio),
            suppressions,
            teams,
        }
    }
}

