/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailContactListSummaryRecord {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "memberCount")]
    pub member_count: f64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl MailContactListSummaryRecord {
    pub fn new(created_at: String, id: String, member_count: f64, name: String, tenant_id: String, updated_at: String) -> MailContactListSummaryRecord {
        MailContactListSummaryRecord {
            created_at,
            id,
            member_count,
            name,
            tenant_id,
            updated_at,
        }
    }
}

