/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailMessagePolicyInput {
    #[serde(rename = "domainQuotas", skip_serializing_if = "Option::is_none")]
    pub domain_quotas: Option<Vec<models::MailQuotaRule>>,
    #[serde(rename = "mailboxQuotas", skip_serializing_if = "Option::is_none")]
    pub mailbox_quotas: Option<Vec<models::MailQuotaRule>>,
    #[serde(rename = "recipientCooldownMs", skip_serializing_if = "Option::is_none")]
    pub recipient_cooldown_ms: Option<f64>,
    #[serde(rename = "recipientQuotas", skip_serializing_if = "Option::is_none")]
    pub recipient_quotas: Option<Vec<models::MailQuotaRule>>,
    #[serde(rename = "sendingWindows", skip_serializing_if = "Option::is_none")]
    pub sending_windows: Option<Vec<models::MailSendingWindow>>,
    #[serde(rename = "tenantQuotas", skip_serializing_if = "Option::is_none")]
    pub tenant_quotas: Option<Vec<models::MailQuotaRule>>,
    #[serde(rename = "timeZone", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
}

impl MailMessagePolicyInput {
    pub fn new() -> MailMessagePolicyInput {
        MailMessagePolicyInput {
            domain_quotas: None,
            mailbox_quotas: None,
            recipient_cooldown_ms: None,
            recipient_quotas: None,
            sending_windows: None,
            tenant_quotas: None,
            time_zone: None,
        }
    }
}

