/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostDeliverabilityDomainHealthResponse200 {
    #[serde(rename = "report")]
    pub report: Box<models::MailDomainHealthReport>,
}

impl MailPostDeliverabilityDomainHealthResponse200 {
    pub fn new(report: models::MailDomainHealthReport) -> MailPostDeliverabilityDomainHealthResponse200 {
        MailPostDeliverabilityDomainHealthResponse200 {
            report: Box::new(report),
        }
    }
}

