/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostDeliverabilityPoolsRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "strategy")]
    pub strategy: Strategy,
}

impl MailPostDeliverabilityPoolsRequest {
    pub fn new(name: String, strategy: Strategy) -> MailPostDeliverabilityPoolsRequest {
        MailPostDeliverabilityPoolsRequest {
            name,
            strategy,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Strategy {
    #[serde(rename = "round_robin")]
    RoundRobin,
    #[serde(rename = "capacity_weighted")]
    CapacityWeighted,
}

impl Default for Strategy {
    fn default() -> Strategy {
        Self::RoundRobin
    }
}

