/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostMailboxesManualRequest {
    #[serde(rename = "dailyLimit", skip_serializing_if = "Option::is_none")]
    pub daily_limit: Option<i32>,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "hourlyLimit", skip_serializing_if = "Option::is_none")]
    pub hourly_limit: Option<i32>,
    #[serde(rename = "imap", skip_serializing_if = "Option::is_none")]
    pub imap: Option<Box<models::MailPostMailboxesManualRequestImap>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "rampEnabled", skip_serializing_if = "Option::is_none")]
    pub ramp_enabled: Option<bool>,
    #[serde(rename = "rampIntervalHours", skip_serializing_if = "Option::is_none")]
    pub ramp_interval_hours: Option<i32>,
    #[serde(rename = "rampStep", skip_serializing_if = "Option::is_none")]
    pub ramp_step: Option<i32>,
    #[serde(rename = "smtp")]
    pub smtp: Box<models::MailPostMailboxesManualRequestSmtp>,
    #[serde(rename = "startingDailyLimit", skip_serializing_if = "Option::is_none")]
    pub starting_daily_limit: Option<i32>,
}

impl MailPostMailboxesManualRequest {
    pub fn new(email: String, smtp: models::MailPostMailboxesManualRequestSmtp) -> MailPostMailboxesManualRequest {
        MailPostMailboxesManualRequest {
            daily_limit: None,
            email,
            hourly_limit: None,
            imap: None,
            name: None,
            ramp_enabled: None,
            ramp_interval_hours: None,
            ramp_step: None,
            smtp: Box::new(smtp),
            starting_daily_limit: None,
        }
    }
}

