/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetWebhooksResponse200 {
    #[serde(rename = "deliveries")]
    pub deliveries: Vec<models::MailWebhookDelivery>,
    #[serde(rename = "subscriptions")]
    pub subscriptions: Vec<models::MailGetWebhooksResponse200SubscriptionsInner>,
}

impl MailGetWebhooksResponse200 {
    pub fn new(deliveries: Vec<models::MailWebhookDelivery>, subscriptions: Vec<models::MailGetWebhooksResponse200SubscriptionsInner>) -> MailGetWebhooksResponse200 {
        MailGetWebhooksResponse200 {
            deliveries,
            subscriptions,
        }
    }
}

