/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailInboxMessageRecord {
    #[serde(rename = "assignedToActorId", skip_serializing_if = "Option::is_none")]
    pub assigned_to_actor_id: Option<String>,
    #[serde(rename = "contactId", skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<String>,
    #[serde(rename = "from")]
    pub from: Box<models::MailConversationEntryFrom>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "inboundClassification")]
    pub inbound_classification: String,
    #[serde(rename = "mailboxId")]
    pub mailbox_id: String,
    #[serde(rename = "outboundMessageId")]
    pub outbound_message_id: String,
    #[serde(rename = "providerEventId")]
    pub provider_event_id: String,
    #[serde(rename = "receivedAt")]
    pub received_at: String,
    #[serde(rename = "replyClassification")]
    pub reply_classification: Box<models::MailReplyClassificationResult>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "threadKey")]
    pub thread_key: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl MailInboxMessageRecord {
    pub fn new(from: models::MailConversationEntryFrom, id: String, inbound_classification: String, mailbox_id: String, outbound_message_id: String, provider_event_id: String, received_at: String, reply_classification: models::MailReplyClassificationResult, status: String, subject: String, tenant_id: String, text: String, thread_key: String, updated_at: String) -> MailInboxMessageRecord {
        MailInboxMessageRecord {
            assigned_to_actor_id: None,
            contact_id: None,
            from: Box::new(from),
            id,
            inbound_classification,
            mailbox_id,
            outbound_message_id,
            provider_event_id,
            received_at,
            reply_classification: Box::new(reply_classification),
            status,
            subject,
            tenant_id,
            text,
            thread_key,
            updated_at,
        }
    }
}

