/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetQueueResponse200 {
    #[serde(rename = "queue")]
    pub queue: Box<models::MailQueueSnapshot>,
}

impl MailGetQueueResponse200 {
    pub fn new(queue: models::MailQueueSnapshot) -> MailGetQueueResponse200 {
        MailGetQueueResponse200 {
            queue: Box::new(queue),
        }
    }
}

