/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostTrackingDomainVerifyResponse200 {
    #[serde(rename = "domain")]
    pub domain: Box<models::MailTrackingDomainRecord>,
    #[serde(rename = "expectedValue")]
    pub expected_value: String,
    #[serde(rename = "recordName")]
    pub record_name: String,
    #[serde(rename = "verified")]
    pub verified: bool,
}

impl MailPostTrackingDomainVerifyResponse200 {
    pub fn new(domain: models::MailTrackingDomainRecord, expected_value: String, record_name: String, verified: bool) -> MailPostTrackingDomainVerifyResponse200 {
        MailPostTrackingDomainVerifyResponse200 {
            domain: Box::new(domain),
            expected_value,
            record_name,
            verified,
        }
    }
}

