/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetChannelsResponse200 {
    #[serde(rename = "email")]
    pub email: Box<models::MailGetChannelsResponse200Email>,
    #[serde(rename = "execution")]
    pub execution: Box<models::MailGetChannelsResponse200Execution>,
    #[serde(rename = "sms")]
    pub sms: Box<models::MailGetChannelsResponse200Sms>,
    #[serde(rename = "whatsapp")]
    pub whatsapp: Box<models::MailGetChannelsResponse200Whatsapp>,
}

impl MailGetChannelsResponse200 {
    pub fn new(email: models::MailGetChannelsResponse200Email, execution: models::MailGetChannelsResponse200Execution, sms: models::MailGetChannelsResponse200Sms, whatsapp: models::MailGetChannelsResponse200Whatsapp) -> MailGetChannelsResponse200 {
        MailGetChannelsResponse200 {
            email: Box::new(email),
            execution: Box::new(execution),
            sms: Box::new(sms),
            whatsapp: Box::new(whatsapp),
        }
    }
}

