/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostSuppressionsResponse200 {
    #[serde(rename = "created")]
    pub created: bool,
}

impl MailPostSuppressionsResponse200 {
    pub fn new(created: bool) -> MailPostSuppressionsResponse200 {
        MailPostSuppressionsResponse200 {
            created,
        }
    }
}

