/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostReplyAutomationsResponse200 {
    #[serde(rename = "automation")]
    pub automation: Box<models::MailReplyAutomationRule>,
}

impl MailPostReplyAutomationsResponse200 {
    pub fn new(automation: models::MailReplyAutomationRule) -> MailPostReplyAutomationsResponse200 {
        MailPostReplyAutomationsResponse200 {
            automation: Box::new(automation),
        }
    }
}

