/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostAnalyticsExportResponse200NextCursorAnyOf {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
}

impl MailPostAnalyticsExportResponse200NextCursorAnyOf {
    pub fn new(created_at: String, id: String) -> MailPostAnalyticsExportResponse200NextCursorAnyOf {
        MailPostAnalyticsExportResponse200NextCursorAnyOf {
            created_at,
            id,
        }
    }
}

