/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailCrmTimelineEvent {
    #[serde(rename = "actorId")]
    pub actor_id: String,
    #[serde(rename = "contactId", skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "occurredAt")]
    pub occurred_at: String,
    #[serde(rename = "payload")]
    pub payload: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl MailCrmTimelineEvent {
    pub fn new(actor_id: String, id: String, occurred_at: String, payload: std::collections::HashMap<String, serde_json::Value>, tenant_id: String, r#type: String) -> MailCrmTimelineEvent {
        MailCrmTimelineEvent {
            actor_id,
            contact_id: None,
            id,
            occurred_at,
            payload,
            tenant_id,
            r#type,
        }
    }
}

