/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailCadenceNode {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "nextNodeId")]
    pub next_node_id: String,
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "experiment")]
    pub experiment: Box<models::MailCadenceWorkflowExperiment>,
    #[serde(rename = "templateId")]
    pub template_id: String,
    #[serde(rename = "templateVersion")]
    pub template_version: f64,
    #[serde(rename = "durationMs")]
    pub duration_ms: f64,
    #[serde(rename = "taskType")]
    pub task_type: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "condition")]
    pub condition: Box<models::MailCadenceNodeAnyOf4AllOfCondition>,
    #[serde(rename = "falseNodeId")]
    pub false_node_id: String,
    #[serde(rename = "trueNodeId")]
    pub true_node_id: String,
    #[serde(rename = "outcome")]
    pub outcome: String,
}

impl MailCadenceNode {
    pub fn new(id: String, name: String, kind: Kind, next_node_id: String, channel: String, experiment: models::MailCadenceWorkflowExperiment, template_id: String, template_version: f64, duration_ms: f64, task_type: String, title: String, condition: models::MailCadenceNodeAnyOf4AllOfCondition, false_node_id: String, true_node_id: String, outcome: String) -> MailCadenceNode {
        MailCadenceNode {
            id,
            name,
            kind,
            next_node_id,
            channel,
            experiment: Box::new(experiment),
            template_id,
            template_version,
            duration_ms,
            task_type,
            title,
            condition: Box::new(condition),
            false_node_id,
            true_node_id,
            outcome,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "stop")]
    Stop,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Stop
    }
}

