/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailMessageAnalyticsOverviewMailboxesInner {
    #[serde(rename = "accepted")]
    pub accepted: f64,
    #[serde(rename = "bounced")]
    pub bounced: f64,
    #[serde(rename = "complained")]
    pub complained: f64,
    #[serde(rename = "mailboxId")]
    pub mailbox_id: String,
    #[serde(rename = "replied")]
    pub replied: f64,
    #[serde(rename = "total")]
    pub total: f64,
}

impl MailMessageAnalyticsOverviewMailboxesInner {
    pub fn new(accepted: f64, bounced: f64, complained: f64, mailbox_id: String, replied: f64, total: f64) -> MailMessageAnalyticsOverviewMailboxesInner {
        MailMessageAnalyticsOverviewMailboxesInner {
            accepted,
            bounced,
            complained,
            mailbox_id,
            replied,
            total,
        }
    }
}

