/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailCampaignProgressMessageCounts {
    #[serde(rename = "auto_replied", skip_serializing_if = "Option::is_none")]
    pub auto_replied: Option<f64>,
    #[serde(rename = "bounced", skip_serializing_if = "Option::is_none")]
    pub bounced: Option<f64>,
    #[serde(rename = "cancelled", skip_serializing_if = "Option::is_none")]
    pub cancelled: Option<f64>,
    #[serde(rename = "complained", skip_serializing_if = "Option::is_none")]
    pub complained: Option<f64>,
    #[serde(rename = "delivered", skip_serializing_if = "Option::is_none")]
    pub delivered: Option<f64>,
    #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<f64>,
    #[serde(rename = "provider_accepted", skip_serializing_if = "Option::is_none")]
    pub provider_accepted: Option<f64>,
    #[serde(rename = "queued", skip_serializing_if = "Option::is_none")]
    pub queued: Option<f64>,
    #[serde(rename = "replied", skip_serializing_if = "Option::is_none")]
    pub replied: Option<f64>,
    #[serde(rename = "retry_scheduled", skip_serializing_if = "Option::is_none")]
    pub retry_scheduled: Option<f64>,
    #[serde(rename = "sending", skip_serializing_if = "Option::is_none")]
    pub sending: Option<f64>,
    #[serde(rename = "suppressed", skip_serializing_if = "Option::is_none")]
    pub suppressed: Option<f64>,
    #[serde(rename = "unsubscribed", skip_serializing_if = "Option::is_none")]
    pub unsubscribed: Option<f64>,
}

impl MailCampaignProgressMessageCounts {
    pub fn new() -> MailCampaignProgressMessageCounts {
        MailCampaignProgressMessageCounts {
            auto_replied: None,
            bounced: None,
            cancelled: None,
            complained: None,
            delivered: None,
            failed: None,
            provider_accepted: None,
            queued: None,
            replied: None,
            retry_scheduled: None,
            sending: None,
            suppressed: None,
            unsubscribed: None,
        }
    }
}

