/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailMailboxHealthRecord {
    #[serde(rename = "accepted7d")]
    pub accepted7d: f64,
    #[serde(rename = "bounced7d")]
    pub bounced7d: f64,
    #[serde(rename = "bounceRate")]
    pub bounce_rate: f64,
    #[serde(rename = "complained7d")]
    pub complained7d: f64,
    #[serde(rename = "complaintRate")]
    pub complaint_rate: f64,
    #[serde(rename = "currentDailyLimit")]
    pub current_daily_limit: f64,
    #[serde(rename = "deferred7d")]
    pub deferred7d: f64,
    #[serde(rename = "deferredRate")]
    pub deferred_rate: f64,
    #[serde(rename = "delivered7d")]
    pub delivered7d: f64,
    #[serde(rename = "healthScore")]
    pub health_score: f64,
    #[serde(rename = "lastSignalAt", skip_serializing_if = "Option::is_none")]
    pub last_signal_at: Option<String>,
    #[serde(rename = "mailboxId")]
    pub mailbox_id: String,
    #[serde(rename = "nextRampAt")]
    pub next_ramp_at: String,
    #[serde(rename = "pauseReason", skip_serializing_if = "Option::is_none")]
    pub pause_reason: Option<String>,
    #[serde(rename = "rampEnabled")]
    pub ramp_enabled: bool,
    #[serde(rename = "rampIntervalHours")]
    pub ramp_interval_hours: f64,
    #[serde(rename = "rampStep")]
    pub ramp_step: f64,
    #[serde(rename = "startingDailyLimit")]
    pub starting_daily_limit: f64,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "targetDailyLimit")]
    pub target_daily_limit: f64,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl MailMailboxHealthRecord {
    pub fn new(accepted7d: f64, bounced7d: f64, bounce_rate: f64, complained7d: f64, complaint_rate: f64, current_daily_limit: f64, deferred7d: f64, deferred_rate: f64, delivered7d: f64, health_score: f64, mailbox_id: String, next_ramp_at: String, ramp_enabled: bool, ramp_interval_hours: f64, ramp_step: f64, starting_daily_limit: f64, status: String, target_daily_limit: f64, tenant_id: String, updated_at: String) -> MailMailboxHealthRecord {
        MailMailboxHealthRecord {
            accepted7d,
            bounced7d,
            bounce_rate,
            complained7d,
            complaint_rate,
            current_daily_limit,
            deferred7d,
            deferred_rate,
            delivered7d,
            health_score,
            last_signal_at: None,
            mailbox_id,
            next_ramp_at,
            pause_reason: None,
            ramp_enabled,
            ramp_interval_hours,
            ramp_step,
            starting_daily_limit,
            status,
            target_daily_limit,
            tenant_id,
            updated_at,
        }
    }
}

