/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCrmTasksResponse201 {
    #[serde(rename = "task")]
    pub task: Box<models::MailCrmTask>,
}

impl MailPostCrmTasksResponse201 {
    pub fn new(task: models::MailCrmTask) -> MailPostCrmTasksResponse201 {
        MailPostCrmTasksResponse201 {
            task: Box::new(task),
        }
    }
}

