/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostInboxByMessageIdResponse200 {
    #[serde(rename = "message", deserialize_with = "Option::deserialize")]
    pub message: Option<Box<models::MailInboxMessageRecord>>,
}

impl MailPostInboxByMessageIdResponse200 {
    pub fn new(message: Option<models::MailInboxMessageRecord>) -> MailPostInboxByMessageIdResponse200 {
        MailPostInboxByMessageIdResponse200 {
            message: message.map(Box::new),
        }
    }
}

