/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostWebhooksResponse201 {
    #[serde(rename = "signingSecret")]
    pub signing_secret: String,
    #[serde(rename = "subscription")]
    pub subscription: Box<models::MailGetWebhooksResponse200SubscriptionsInner>,
}

impl MailPostWebhooksResponse201 {
    pub fn new(signing_secret: String, subscription: models::MailGetWebhooksResponse200SubscriptionsInner) -> MailPostWebhooksResponse201 {
        MailPostWebhooksResponse201 {
            signing_secret,
            subscription: Box::new(subscription),
        }
    }
}

