/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailMailboxRecord {
    #[serde(rename = "address")]
    pub address: Box<models::MailMailAddress>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "dailyLimit")]
    pub daily_limit: f64,
    #[serde(rename = "hourlyLimit")]
    pub hourly_limit: f64,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "provider")]
    pub provider: Box<models::MailMailboxProviderKind>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl MailMailboxRecord {
    pub fn new(address: models::MailMailAddress, created_at: String, daily_limit: f64, hourly_limit: f64, id: String, provider: models::MailMailboxProviderKind, status: String, tenant_id: String, updated_at: String) -> MailMailboxRecord {
        MailMailboxRecord {
            address: Box::new(address),
            created_at,
            daily_limit,
            hourly_limit,
            id,
            provider: Box::new(provider),
            status,
            tenant_id,
            updated_at,
        }
    }
}

