/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostDeliverabilityPoolsResponse201Pool {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "members")]
    pub members: Vec<models::MailMailboxPoolMember>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "strategy")]
    pub strategy: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl MailPostDeliverabilityPoolsResponse201Pool {
    pub fn new(created_at: String, id: String, members: Vec<models::MailMailboxPoolMember>, name: String, strategy: String, tenant_id: String, updated_at: String) -> MailPostDeliverabilityPoolsResponse201Pool {
        MailPostDeliverabilityPoolsResponse201Pool {
            created_at,
            id,
            members,
            name,
            strategy,
            tenant_id,
            updated_at,
        }
    }
}

