/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetSignaturesResponse200 {
    #[serde(rename = "candidates")]
    pub candidates: Vec<models::MailSignatureCandidate>,
    #[serde(rename = "nextCursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

impl MailGetSignaturesResponse200 {
    pub fn new(candidates: Vec<models::MailSignatureCandidate>) -> MailGetSignaturesResponse200 {
        MailGetSignaturesResponse200 {
            candidates,
            next_cursor: None,
        }
    }
}

