/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetOverviewResponse200Inbox {
    #[serde(rename = "needsReply")]
    pub needs_reply: f64,
    #[serde(rename = "recent")]
    pub recent: Vec<models::MailInboxMessageRecord>,
    #[serde(rename = "unread")]
    pub unread: f64,
}

impl MailGetOverviewResponse200Inbox {
    pub fn new(needs_reply: f64, recent: Vec<models::MailInboxMessageRecord>, unread: f64) -> MailGetOverviewResponse200Inbox {
        MailGetOverviewResponse200Inbox {
            needs_reply,
            recent,
            unread,
        }
    }
}

