/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailMessagePolicy {
    #[serde(rename = "domainQuotas")]
    pub domain_quotas: Vec<models::MailQuotaRule>,
    #[serde(rename = "mailboxQuotas")]
    pub mailbox_quotas: Vec<models::MailQuotaRule>,
    #[serde(rename = "recipientCooldownMs", skip_serializing_if = "Option::is_none")]
    pub recipient_cooldown_ms: Option<f64>,
    #[serde(rename = "recipientQuotas")]
    pub recipient_quotas: Vec<models::MailQuotaRule>,
    #[serde(rename = "sendingWindows")]
    pub sending_windows: Vec<models::MailSendingWindow>,
    #[serde(rename = "tenantQuotas")]
    pub tenant_quotas: Vec<models::MailQuotaRule>,
    #[serde(rename = "timeZone")]
    pub time_zone: String,
}

impl MailMessagePolicy {
    pub fn new(domain_quotas: Vec<models::MailQuotaRule>, mailbox_quotas: Vec<models::MailQuotaRule>, recipient_quotas: Vec<models::MailQuotaRule>, sending_windows: Vec<models::MailSendingWindow>, tenant_quotas: Vec<models::MailQuotaRule>, time_zone: String) -> MailMessagePolicy {
        MailMessagePolicy {
            domain_quotas,
            mailbox_quotas,
            recipient_cooldown_ms: None,
            recipient_quotas,
            sending_windows,
            tenant_quotas,
            time_zone,
        }
    }
}

