/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailMessageTemplateVersion {
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "createdByActorId")]
    pub created_by_actor_id: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "variables")]
    pub variables: Vec<String>,
    #[serde(rename = "version")]
    pub version: f64,
    #[serde(rename = "whatsappApproval", skip_serializing_if = "Option::is_none")]
    pub whatsapp_approval: Option<Box<models::MailMessageTemplateVersionWhatsappApproval>>,
}

impl MailMessageTemplateVersion {
    pub fn new(body: String, channel: String, created_at: String, created_by_actor_id: String, id: String, name: String, status: String, tenant_id: String, variables: Vec<String>, version: f64) -> MailMessageTemplateVersion {
        MailMessageTemplateVersion {
            body,
            channel,
            created_at,
            created_by_actor_id,
            id,
            name,
            status,
            subject: None,
            tenant_id,
            variables,
            version,
            whatsapp_approval: None,
        }
    }
}

