/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostAnalyticsExportResponse200 {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "contentType")]
    pub content_type: ContentType,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "nextCursor")]
    pub next_cursor: Box<models::MailPostAnalyticsExportResponse200NextCursor>,
    #[serde(rename = "rowCount")]
    pub row_count: f64,
}

impl MailPostAnalyticsExportResponse200 {
    pub fn new(content: String, content_type: ContentType, filename: String, next_cursor: models::MailPostAnalyticsExportResponse200NextCursor, row_count: f64) -> MailPostAnalyticsExportResponse200 {
        MailPostAnalyticsExportResponse200 {
            content,
            content_type,
            filename,
            next_cursor: Box::new(next_cursor),
            row_count,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentType {
    #[serde(rename = "text/csv; charset=utf-8")]
    TextSlashCsvSemicolonCharsetEqualUtf8,
}

impl Default for ContentType {
    fn default() -> ContentType {
        Self::TextSlashCsvSemicolonCharsetEqualUtf8
    }
}

