/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailImapCursor {
    #[serde(rename = "lastUid")]
    pub last_uid: f64,
    #[serde(rename = "mailboxPath")]
    pub mailbox_path: String,
    #[serde(rename = "uidValidity")]
    pub uid_validity: String,
}

impl MailImapCursor {
    pub fn new(last_uid: f64, mailbox_path: String, uid_validity: String) -> MailImapCursor {
        MailImapCursor {
            last_uid,
            mailbox_path,
            uid_validity,
        }
    }
}

