/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostMessagesResponse201 {
    #[serde(rename = "message")]
    pub message: Box<models::MailMessageRecord>,
}

impl MailPostMessagesResponse201 {
    pub fn new(message: models::MailMessageRecord) -> MailPostMessagesResponse201 {
        MailPostMessagesResponse201 {
            message: Box::new(message),
        }
    }
}

