/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetPortfolioResponse200Portfolio {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "createdByActorId")]
    pub created_by_actor_id: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "ownerTeamId")]
    pub owner_team_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl MailGetPortfolioResponse200Portfolio {
    pub fn new(created_at: String, created_by_actor_id: String, id: String, name: String, owner_team_id: String, updated_at: String) -> MailGetPortfolioResponse200Portfolio {
        MailGetPortfolioResponse200Portfolio {
            created_at,
            created_by_actor_id,
            id,
            name,
            owner_team_id,
            updated_at,
        }
    }
}

