/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailCampaignProgress {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "messageCounts")]
    pub message_counts: Box<models::MailCampaignProgressMessageCounts>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "recipientCount")]
    pub recipient_count: f64,
    #[serde(rename = "sequenceRunIds")]
    pub sequence_run_ids: Vec<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "totalMessages")]
    pub total_messages: f64,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl MailCampaignProgress {
    pub fn new(created_at: String, id: String, message_counts: models::MailCampaignProgressMessageCounts, name: String, recipient_count: f64, sequence_run_ids: Vec<String>, status: String, tenant_id: String, total_messages: f64, updated_at: String) -> MailCampaignProgress {
        MailCampaignProgress {
            created_at,
            id,
            message_counts: Box::new(message_counts),
            name,
            recipient_count,
            sequence_run_ids,
            status,
            tenant_id,
            total_messages,
            updated_at,
        }
    }
}

