/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostCadencesRequestStopConditions {
    #[serde(rename = "meetingBooked")]
    pub meeting_booked: MeetingBooked,
    #[serde(rename = "negativeReply")]
    pub negative_reply: NegativeReply,
    #[serde(rename = "outOfOffice")]
    pub out_of_office: OutOfOffice,
    #[serde(rename = "positiveReply")]
    pub positive_reply: PositiveReply,
    #[serde(rename = "unknownHumanReply")]
    pub unknown_human_reply: UnknownHumanReply,
}

impl MailPostCadencesRequestStopConditions {
    pub fn new(meeting_booked: MeetingBooked, negative_reply: NegativeReply, out_of_office: OutOfOffice, positive_reply: PositiveReply, unknown_human_reply: UnknownHumanReply) -> MailPostCadencesRequestStopConditions {
        MailPostCadencesRequestStopConditions {
            meeting_booked,
            negative_reply,
            out_of_office,
            positive_reply,
            unknown_human_reply,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MeetingBooked {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "continue")]
    Continue,
}

impl Default for MeetingBooked {
    fn default() -> MeetingBooked {
        Self::Stop
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NegativeReply {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "continue")]
    Continue,
}

impl Default for NegativeReply {
    fn default() -> NegativeReply {
        Self::Stop
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OutOfOffice {
    #[serde(rename = "pause")]
    Pause,
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "continue")]
    Continue,
}

impl Default for OutOfOffice {
    fn default() -> OutOfOffice {
        Self::Pause
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PositiveReply {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "continue")]
    Continue,
}

impl Default for PositiveReply {
    fn default() -> PositiveReply {
        Self::Stop
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnknownHumanReply {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "continue")]
    Continue,
}

impl Default for UnknownHumanReply {
    fn default() -> UnknownHumanReply {
        Self::Stop
    }
}

