/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostInboxByMessageIdReplyRequest {
    #[serde(rename = "clientRequestId")]
    pub client_request_id: String,
    #[serde(rename = "text")]
    pub text: String,
}

impl MailPostInboxByMessageIdReplyRequest {
    pub fn new(client_request_id: String, text: String) -> MailPostInboxByMessageIdReplyRequest {
        MailPostInboxByMessageIdReplyRequest {
            client_request_id,
            text,
        }
    }
}

