/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailReplyAutomationRuleActions {
    #[serde(rename = "assignToActorId", skip_serializing_if = "Option::is_none")]
    pub assign_to_actor_id: Option<String>,
    #[serde(rename = "stage", skip_serializing_if = "Option::is_none")]
    pub stage: Option<String>,
    #[serde(rename = "stopCadences")]
    pub stop_cadences: bool,
    #[serde(rename = "task", skip_serializing_if = "Option::is_none")]
    pub task: Option<Box<models::MailReplyAutomationRuleActionsTask>>,
}

impl MailReplyAutomationRuleActions {
    pub fn new(stop_cadences: bool) -> MailReplyAutomationRuleActions {
        MailReplyAutomationRuleActions {
            assign_to_actor_id: None,
            stage: None,
            stop_cadences,
            task: None,
        }
    }
}

