/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailMessageAnalyticsOverviewVariantsInner {
    #[serde(rename = "accepted")]
    pub accepted: f64,
    #[serde(rename = "bounced")]
    pub bounced: f64,
    #[serde(rename = "campaignId", skip_serializing_if = "Option::is_none")]
    pub campaign_id: Option<String>,
    #[serde(rename = "complained")]
    pub complained: f64,
    #[serde(rename = "experimentId", skip_serializing_if = "Option::is_none")]
    pub experiment_id: Option<String>,
    #[serde(rename = "experimentName", skip_serializing_if = "Option::is_none")]
    pub experiment_name: Option<String>,
    #[serde(rename = "replied")]
    pub replied: f64,
    #[serde(rename = "stepId", skip_serializing_if = "Option::is_none")]
    pub step_id: Option<String>,
    #[serde(rename = "total")]
    pub total: f64,
    #[serde(rename = "variantId")]
    pub variant_id: String,
}

impl MailMessageAnalyticsOverviewVariantsInner {
    pub fn new(accepted: f64, bounced: f64, complained: f64, replied: f64, total: f64, variant_id: String) -> MailMessageAnalyticsOverviewVariantsInner {
        MailMessageAnalyticsOverviewVariantsInner {
            accepted,
            bounced,
            campaign_id: None,
            complained,
            experiment_id: None,
            experiment_name: None,
            replied,
            step_id: None,
            total,
            variant_id,
        }
    }
}

