/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPatchCampaignsByCampaignIdRequestStepsInner {
    #[serde(rename = "delayMs")]
    pub delay_ms: i32,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "variants", skip_serializing_if = "Option::is_none")]
    pub variants: Option<Vec<models::MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner>>,
}

impl MailPatchCampaignsByCampaignIdRequestStepsInner {
    pub fn new(delay_ms: i32, subject: String, text: String) -> MailPatchCampaignsByCampaignIdRequestStepsInner {
        MailPatchCampaignsByCampaignIdRequestStepsInner {
            delay_ms,
            html: None,
            id: None,
            subject,
            text,
            variants: None,
        }
    }
}

