/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailReplyAutomationRule {
    #[serde(rename = "actions")]
    pub actions: Box<models::MailReplyAutomationRuleActions>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "labels")]
    pub labels: Vec<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "priority")]
    pub priority: f64,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl MailReplyAutomationRule {
    pub fn new(actions: models::MailReplyAutomationRuleActions, created_at: String, enabled: bool, id: String, labels: Vec<String>, name: String, priority: f64, tenant_id: String, updated_at: String) -> MailReplyAutomationRule {
        MailReplyAutomationRule {
            actions: Box::new(actions),
            created_at,
            enabled,
            id,
            labels,
            name,
            priority,
            tenant_id,
            updated_at,
        }
    }
}

