/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MailPostCadencesRequestNodesInnerAnyOf {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "nextNodeId")]
    pub next_node_id: String,
}

impl MailPostCadencesRequestNodesInnerAnyOf {
    pub fn new(id: String, kind: Kind, name: String, next_node_id: String) -> MailPostCadencesRequestNodesInnerAnyOf {
        MailPostCadencesRequestNodesInnerAnyOf {
            id,
            kind,
            name,
            next_node_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "start")]
    Start,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Start
    }
}

