/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetChannelsResponse200Execution {
    #[serde(rename = "cadence")]
    pub cadence: bool,
    #[serde(rename = "inbound")]
    pub inbound: bool,
    #[serde(rename = "outbound")]
    pub outbound: bool,
}

impl MailGetChannelsResponse200Execution {
    pub fn new(cadence: bool, inbound: bool, outbound: bool) -> MailGetChannelsResponse200Execution {
        MailGetChannelsResponse200Execution {
            cadence,
            inbound,
            outbound,
        }
    }
}

