/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostPortfolioSuppressionsResponse200 {
    #[serde(rename = "appliedTeamIds")]
    pub applied_team_ids: Vec<String>,
    #[serde(rename = "suppression")]
    pub suppression: Box<models::MailMailPortfolioSuppression>,
}

impl MailPostPortfolioSuppressionsResponse200 {
    pub fn new(applied_team_ids: Vec<String>, suppression: models::MailMailPortfolioSuppression) -> MailPostPortfolioSuppressionsResponse200 {
        MailPostPortfolioSuppressionsResponse200 {
            applied_team_ids,
            suppression: Box::new(suppression),
        }
    }
}

