/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailPostOauthBeginResponse200 {
    #[serde(rename = "authorizationUrl")]
    pub authorization_url: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
}

impl MailPostOauthBeginResponse200 {
    pub fn new(authorization_url: String, expires_at: String) -> MailPostOauthBeginResponse200 {
        MailPostOauthBeginResponse200 {
            authorization_url,
            expires_at,
        }
    }
}

