/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailCadenceRunRecord {
    #[serde(rename = "actorId")]
    pub actor_id: String,
    #[serde(rename = "attemptCount")]
    pub attempt_count: f64,
    #[serde(rename = "audienceListId", skip_serializing_if = "Option::is_none")]
    pub audience_list_id: Option<String>,
    #[serde(rename = "cadenceId")]
    pub cadence_id: String,
    #[serde(rename = "cadenceVersion")]
    pub cadence_version: f64,
    #[serde(rename = "campaignId", skip_serializing_if = "Option::is_none")]
    pub campaign_id: Option<String>,
    #[serde(rename = "campaignName", skip_serializing_if = "Option::is_none")]
    pub campaign_name: Option<String>,
    #[serde(rename = "contactId")]
    pub contact_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "currentNodeId")]
    pub current_node_id: String,
    #[serde(rename = "dueAt")]
    pub due_at: String,
    #[serde(rename = "experimentContexts", skip_serializing_if = "Option::is_none")]
    pub experiment_contexts: Option<Vec<models::MailCadenceExperimentContext>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "lastAcceptedMessageId", skip_serializing_if = "Option::is_none")]
    pub last_accepted_message_id: Option<String>,
    #[serde(rename = "lastError", skip_serializing_if = "Option::is_none")]
    pub last_error: Option<String>,
    #[serde(rename = "leaseExpiresAt", skip_serializing_if = "Option::is_none")]
    pub lease_expires_at: Option<String>,
    #[serde(rename = "leaseOwner", skip_serializing_if = "Option::is_none")]
    pub lease_owner: Option<String>,
    #[serde(rename = "mailboxId")]
    pub mailbox_id: String,
    #[serde(rename = "outcome", skip_serializing_if = "Option::is_none")]
    pub outcome: Option<String>,
    #[serde(rename = "pendingMessageId", skip_serializing_if = "Option::is_none")]
    pub pending_message_id: Option<String>,
    #[serde(rename = "pendingNextNodeId", skip_serializing_if = "Option::is_none")]
    pub pending_next_node_id: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "taskId", skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "version")]
    pub version: f64,
}

impl MailCadenceRunRecord {
    pub fn new(actor_id: String, attempt_count: f64, cadence_id: String, cadence_version: f64, contact_id: String, created_at: String, current_node_id: String, due_at: String, id: String, idempotency_key: String, mailbox_id: String, status: String, tenant_id: String, updated_at: String, version: f64) -> MailCadenceRunRecord {
        MailCadenceRunRecord {
            actor_id,
            attempt_count,
            audience_list_id: None,
            cadence_id,
            cadence_version,
            campaign_id: None,
            campaign_name: None,
            contact_id,
            created_at,
            current_node_id,
            due_at,
            experiment_contexts: None,
            id,
            idempotency_key,
            last_accepted_message_id: None,
            last_error: None,
            lease_expires_at: None,
            lease_owner: None,
            mailbox_id,
            outcome: None,
            pending_message_id: None,
            pending_next_node_id: None,
            status,
            task_id: None,
            tenant_id,
            updated_at,
            version,
        }
    }
}

