/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailGetPortfolioOverviewResponse200 {
    #[serde(rename = "generatedAt")]
    pub generated_at: String,
    #[serde(rename = "portfolio")]
    pub portfolio: Box<models::MailMailPortfolio>,
    #[serde(rename = "rows")]
    pub rows: Vec<models::MailMailPortfolioOverviewRow>,
}

impl MailGetPortfolioOverviewResponse200 {
    pub fn new(generated_at: String, portfolio: models::MailMailPortfolio, rows: Vec<models::MailMailPortfolioOverviewRow>) -> MailGetPortfolioOverviewResponse200 {
        MailGetPortfolioOverviewResponse200 {
            generated_at,
            portfolio: Box::new(portfolio),
            rows,
        }
    }
}

