/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpIdentity {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "issuer")]
    pub issuer: String,
    #[serde(rename = "lastUsedAt", deserialize_with = "Option::deserialize")]
    pub last_used_at: Option<String>,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl McpIdentity {
    pub fn new(created_at: String, enabled: bool, id: String, issuer: String, last_used_at: Option<String>, scopes: Vec<String>, team_id: String, updated_at: String, user_id: String) -> McpIdentity {
        McpIdentity {
            created_at,
            enabled,
            id,
            issuer,
            last_used_at,
            scopes,
            team_id,
            updated_at,
            user_id,
        }
    }
}

