/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpIdentityResponse {
    #[serde(rename = "identity")]
    pub identity: models::McpIdentity,
}

impl McpIdentityResponse {
    pub fn new(identity: models::McpIdentity) -> McpIdentityResponse {
        McpIdentityResponse {
            identity,
        }
    }
}

