/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductCompanyListAddOutput {
    #[serde(rename = "added")]
    pub added: bool,
    #[serde(rename = "companyId")]
    pub company_id: uuid::Uuid,
    #[serde(rename = "listId")]
    pub list_id: uuid::Uuid,
}

impl ProductCompanyListAddOutput {
    pub fn new(added: bool, company_id: uuid::Uuid, list_id: uuid::Uuid) -> ProductCompanyListAddOutput {
        ProductCompanyListAddOutput {
            added,
            company_id,
            list_id,
        }
    }
}

