/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductCompanyUpdateOutput {
    #[serde(rename = "companyId")]
    pub company_id: uuid::Uuid,
    #[serde(rename = "employeeRange", deserialize_with = "Option::deserialize")]
    pub employee_range: Option<String>,
    #[serde(rename = "industry", deserialize_with = "Option::deserialize")]
    pub industry: Option<String>,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
}

impl ProductCompanyUpdateOutput {
    pub fn new(company_id: uuid::Uuid, employee_range: Option<String>, industry: Option<String>, name: Option<String>) -> ProductCompanyUpdateOutput {
        ProductCompanyUpdateOutput {
            company_id,
            employee_range,
            industry,
            name,
        }
    }
}

