/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductLeadDeleteInput {
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "leadId")]
    pub lead_id: uuid::Uuid,
}

impl ProductLeadDeleteInput {
    pub fn new(idempotency_key: String, lead_id: uuid::Uuid) -> ProductLeadDeleteInput {
        ProductLeadDeleteInput {
            idempotency_key,
            lead_id,
        }
    }
}

