/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductCombinedEnrichOutput {
    #[serde(rename = "company")]
    pub company: Box<models::ProductCompany>,
    #[serde(rename = "person")]
    pub person: Box<models::ProductPerson>,
}

impl ProductCombinedEnrichOutput {
    pub fn new(company: models::ProductCompany, person: models::ProductPerson) -> ProductCombinedEnrichOutput {
        ProductCombinedEnrichOutput {
            company: Box::new(company),
            person: Box::new(person),
        }
    }
}

