/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductLeadListAddLeadOutput {
    #[serde(rename = "added")]
    pub added: bool,
    #[serde(rename = "leadId")]
    pub lead_id: uuid::Uuid,
    #[serde(rename = "listId")]
    pub list_id: uuid::Uuid,
}

impl ProductLeadListAddLeadOutput {
    pub fn new(added: bool, lead_id: uuid::Uuid, list_id: uuid::Uuid) -> ProductLeadListAddLeadOutput {
        ProductLeadListAddLeadOutput {
            added,
            lead_id,
            list_id,
        }
    }
}

