/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductTeamMember {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "role")]
    pub role: String,
}

impl ProductTeamMember {
    pub fn new(email: String, id: uuid::Uuid, role: String) -> ProductTeamMember {
        ProductTeamMember {
            email,
            id,
            role,
        }
    }
}

