/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductLeadTagRemoveInput {
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "leadId")]
    pub lead_id: uuid::Uuid,
    #[serde(rename = "tagId")]
    pub tag_id: uuid::Uuid,
}

impl ProductLeadTagRemoveInput {
    pub fn new(idempotency_key: String, lead_id: uuid::Uuid, tag_id: uuid::Uuid) -> ProductLeadTagRemoveInput {
        ProductLeadTagRemoveInput {
            idempotency_key,
            lead_id,
            tag_id,
        }
    }
}

