/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductLeadListsListOutput {
    #[serde(rename = "items")]
    pub items: Vec<models::ProductLeadList>,
}

impl ProductLeadListsListOutput {
    pub fn new(items: Vec<models::ProductLeadList>) -> ProductLeadListsListOutput {
        ProductLeadListsListOutput {
            items,
        }
    }
}

