/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductCompanyListAddInput {
    #[serde(rename = "companyId")]
    pub company_id: uuid::Uuid,
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "listId")]
    pub list_id: uuid::Uuid,
}

impl ProductCompanyListAddInput {
    pub fn new(company_id: uuid::Uuid, idempotency_key: String, list_id: uuid::Uuid) -> ProductCompanyListAddInput {
        ProductCompanyListAddInput {
            company_id,
            idempotency_key,
            list_id,
        }
    }
}

