/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductLeadTagRemoveOutput {
    #[serde(rename = "leadId")]
    pub lead_id: uuid::Uuid,
    #[serde(rename = "removed")]
    pub removed: bool,
    #[serde(rename = "tagId")]
    pub tag_id: uuid::Uuid,
}

impl ProductLeadTagRemoveOutput {
    pub fn new(lead_id: uuid::Uuid, removed: bool, tag_id: uuid::Uuid) -> ProductLeadTagRemoveOutput {
        ProductLeadTagRemoveOutput {
            lead_id,
            removed,
            tag_id,
        }
    }
}

