/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductDomainFinderInput {
    /// The server applies trim before validating {\"type\":\"string\",\"minLength\":1,\"maxLength\":500}.
    #[serde(rename = "company")]
    pub company: String,
}

impl ProductDomainFinderInput {
    pub fn new(company: String) -> ProductDomainFinderInput {
        ProductDomainFinderInput {
            company,
        }
    }
}

