/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductLeadListDeleteOutput {
    #[serde(rename = "deleted")]
    pub deleted: bool,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl ProductLeadListDeleteOutput {
    pub fn new(deleted: bool, id: uuid::Uuid) -> ProductLeadListDeleteOutput {
        ProductLeadListDeleteOutput {
            deleted,
            id,
        }
    }
}

