/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductConnectedAppPushOutput {
    #[serde(rename = "jobId")]
    pub job_id: uuid::Uuid,
    #[serde(rename = "queued")]
    pub queued: bool,
    #[serde(rename = "status")]
    pub status: String,
}

impl ProductConnectedAppPushOutput {
    pub fn new(job_id: uuid::Uuid, queued: bool, status: String) -> ProductConnectedAppPushOutput {
        ProductConnectedAppPushOutput {
            job_id,
            queued,
            status,
        }
    }
}

