/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductSequenceRecipientsAddInputRecipientsInner {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "leadId", skip_serializing_if = "Option::is_none")]
    pub lead_id: Option<uuid::Uuid>,
}

impl ProductSequenceRecipientsAddInputRecipientsInner {
    pub fn new(email: String) -> ProductSequenceRecipientsAddInputRecipientsInner {
        ProductSequenceRecipientsAddInputRecipientsInner {
            email,
            lead_id: None,
        }
    }
}

