/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductSequencesListExecution {
    #[serde(rename = "executionId", deserialize_with = "Option::deserialize")]
    pub execution_id: Option<String>,
    #[serde(rename = "output")]
    pub output: Box<models::ProductSequencesListOutput>,
    #[serde(rename = "replay")]
    pub replay: bool,
    #[serde(rename = "tool")]
    pub tool: Tool,
}

impl ProductSequencesListExecution {
    pub fn new(execution_id: Option<String>, output: models::ProductSequencesListOutput, replay: bool, tool: Tool) -> ProductSequencesListExecution {
        ProductSequencesListExecution {
            execution_id,
            output: Box::new(output),
            replay,
            tool,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Tool {
    #[serde(rename = "sequences_list")]
    SequencesList,
}

impl Default for Tool {
    fn default() -> Tool {
        Self::SequencesList
    }
}

