/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductSequenceStartInput {
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "sequenceId")]
    pub sequence_id: uuid::Uuid,
}

impl ProductSequenceStartInput {
    pub fn new(idempotency_key: String, sequence_id: uuid::Uuid) -> ProductSequenceStartInput {
        ProductSequenceStartInput {
            idempotency_key,
            sequence_id,
        }
    }
}

