/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductRecipient {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "leadId", deserialize_with = "Option::deserialize")]
    pub lead_id: Option<uuid::Uuid>,
    #[serde(rename = "sequenceId")]
    pub sequence_id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: String,
}

impl ProductRecipient {
    pub fn new(email: String, id: uuid::Uuid, lead_id: Option<uuid::Uuid>, sequence_id: uuid::Uuid, status: String) -> ProductRecipient {
        ProductRecipient {
            email,
            id,
            lead_id,
            sequence_id,
            status,
        }
    }
}

