/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductSequenceRecipientsAddExecution {
    #[serde(rename = "executionId")]
    pub execution_id: uuid::Uuid,
    #[serde(rename = "output")]
    pub output: Box<models::ProductSequenceRecipientsAddOutput>,
    #[serde(rename = "replay")]
    pub replay: bool,
    #[serde(rename = "tool")]
    pub tool: Tool,
}

impl ProductSequenceRecipientsAddExecution {
    pub fn new(execution_id: uuid::Uuid, output: models::ProductSequenceRecipientsAddOutput, replay: bool, tool: Tool) -> ProductSequenceRecipientsAddExecution {
        ProductSequenceRecipientsAddExecution {
            execution_id,
            output: Box::new(output),
            replay,
            tool,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Tool {
    #[serde(rename = "sequence_recipients_add")]
    SequenceRecipientsAdd,
}

impl Default for Tool {
    fn default() -> Tool {
        Self::SequenceRecipientsAdd
    }
}

