/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductLead {
    #[serde(rename = "company", deserialize_with = "Option::deserialize")]
    pub company: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "firstName", deserialize_with = "Option::deserialize")]
    pub first_name: Option<String>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "lastName", deserialize_with = "Option::deserialize")]
    pub last_name: Option<String>,
    #[serde(rename = "position", deserialize_with = "Option::deserialize")]
    pub position: Option<String>,
    #[serde(rename = "tags", deserialize_with = "Option::deserialize")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "verificationStatus", deserialize_with = "Option::deserialize")]
    pub verification_status: Option<String>,
}

impl ProductLead {
    pub fn new(company: Option<String>, created_at: String, email: String, first_name: Option<String>, id: uuid::Uuid, last_name: Option<String>, position: Option<String>, tags: Option<Vec<String>>, updated_at: String, verification_status: Option<String>) -> ProductLead {
        ProductLead {
            company,
            created_at,
            email,
            first_name,
            id,
            last_name,
            position,
            tags,
            updated_at,
            verification_status,
        }
    }
}

