/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductLeadListRemoveLeadOutput {
    #[serde(rename = "leadId")]
    pub lead_id: uuid::Uuid,
    #[serde(rename = "listId")]
    pub list_id: uuid::Uuid,
    #[serde(rename = "removed")]
    pub removed: bool,
}

impl ProductLeadListRemoveLeadOutput {
    pub fn new(lead_id: uuid::Uuid, list_id: uuid::Uuid, removed: bool) -> ProductLeadListRemoveLeadOutput {
        ProductLeadListRemoveLeadOutput {
            lead_id,
            list_id,
            removed,
        }
    }
}

