/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductCompanyDeleteOutput {
    #[serde(rename = "companyId")]
    pub company_id: uuid::Uuid,
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl ProductCompanyDeleteOutput {
    pub fn new(company_id: uuid::Uuid, deleted: bool) -> ProductCompanyDeleteOutput {
        ProductCompanyDeleteOutput {
            company_id,
            deleted,
        }
    }
}

