/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductCompanyList {
    #[serde(rename = "companyCount")]
    pub company_count: i32,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl ProductCompanyList {
    pub fn new(company_count: i32, created_at: String, id: uuid::Uuid, name: String, updated_at: String) -> ProductCompanyList {
        ProductCompanyList {
            company_count,
            created_at,
            id,
            name,
            updated_at,
        }
    }
}

