/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductLeadsListOutput {
    #[serde(rename = "items")]
    pub items: Vec<models::ProductLead>,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "offset")]
    pub offset: i32,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ProductLeadsListOutput {
    pub fn new(items: Vec<models::ProductLead>, limit: i32, offset: i32, total: i32) -> ProductLeadsListOutput {
        ProductLeadsListOutput {
            items,
            limit,
            offset,
            total,
        }
    }
}

