/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductCompanyEnrichInput {
    /// The server applies trim, toLowerCase before validating {\"type\":\"string\",\"pattern\":\"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\\\.)+[a-z]{2,63}$\"}.
    #[serde(rename = "domain")]
    pub domain: String,
}

impl ProductCompanyEnrichInput {
    pub fn new(domain: String) -> ProductCompanyEnrichInput {
        ProductCompanyEnrichInput {
            domain,
        }
    }
}

