/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductSequence {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "recipientCount")]
    pub recipient_count: i32,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl ProductSequence {
    pub fn new(created_at: String, id: uuid::Uuid, name: String, recipient_count: i32, status: String, updated_at: String) -> ProductSequence {
        ProductSequence {
            created_at,
            id,
            name,
            recipient_count,
            status,
            updated_at,
        }
    }
}

