/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductLeadGetInput {
    #[serde(rename = "leadId")]
    pub lead_id: uuid::Uuid,
}

impl ProductLeadGetInput {
    pub fn new(lead_id: uuid::Uuid) -> ProductLeadGetInput {
        ProductLeadGetInput {
            lead_id,
        }
    }
}

