/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductConnectedAppPushInput {
    #[serde(rename = "connectionId")]
    pub connection_id: uuid::Uuid,
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "leadIds")]
    pub lead_ids: Vec<uuid::Uuid>,
}

impl ProductConnectedAppPushInput {
    pub fn new(connection_id: uuid::Uuid, idempotency_key: String, lead_ids: Vec<uuid::Uuid>) -> ProductConnectedAppPushInput {
        ProductConnectedAppPushInput {
            connection_id,
            idempotency_key,
            lead_ids,
        }
    }
}

