/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductSequenceRecipientAddInput {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "leadId", skip_serializing_if = "Option::is_none")]
    pub lead_id: Option<uuid::Uuid>,
    #[serde(rename = "sequenceId")]
    pub sequence_id: uuid::Uuid,
}

impl ProductSequenceRecipientAddInput {
    pub fn new(email: String, idempotency_key: String, sequence_id: uuid::Uuid) -> ProductSequenceRecipientAddInput {
        ProductSequenceRecipientAddInput {
            email,
            idempotency_key,
            lead_id: None,
            sequence_id,
        }
    }
}

