/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductLeadBulkDeleteInput {
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "leadIds")]
    pub lead_ids: Vec<uuid::Uuid>,
}

impl ProductLeadBulkDeleteInput {
    pub fn new(idempotency_key: String, lead_ids: Vec<uuid::Uuid>) -> ProductLeadBulkDeleteInput {
        ProductLeadBulkDeleteInput {
            idempotency_key,
            lead_ids,
        }
    }
}

