/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicStats {
    #[serde(rename = "emails")]
    pub emails: i32,
    #[serde(rename = "mentions")]
    pub mentions: i32,
    #[serde(rename = "version")]
    pub version: String,
}

impl PublicStats {
    pub fn new(emails: i32, mentions: i32, version: String) -> PublicStats {
        PublicStats {
            emails,
            mentions,
            version,
        }
    }
}

