/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueIntegrationLeadExportRequest {
    #[serde(rename = "deselectedLeadIds", skip_serializing_if = "Option::is_none")]
    pub deselected_lead_ids: Option<Vec<String>>,
    #[serde(rename = "leadIds", skip_serializing_if = "Option::is_none")]
    pub lead_ids: Option<Vec<String>>,
    #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    #[serde(rename = "selectionScopes", skip_serializing_if = "Option::is_none")]
    pub selection_scopes: Option<Vec<models::QueueIntegrationLeadExportRequestSelectionScopesInner>>,
}

impl QueueIntegrationLeadExportRequest {
    pub fn new() -> QueueIntegrationLeadExportRequest {
        QueueIntegrationLeadExportRequest {
            deselected_lead_ids: None,
            lead_ids: None,
            request_id: None,
            selection_scopes: None,
        }
    }
}

