/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueuedIntegrationJob {
    #[serde(rename = "attempt")]
    pub attempt: i32,
    #[serde(rename = "cancel_requested_at", deserialize_with = "Option::deserialize")]
    pub cancel_requested_at: Option<String>,
    #[serde(rename = "cancel_requested_by_user_id", deserialize_with = "Option::deserialize")]
    pub cancel_requested_by_user_id: Option<String>,
    #[serde(rename = "canonical_event_id", deserialize_with = "Option::deserialize")]
    pub canonical_event_id: Option<String>,
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    #[serde(rename = "counters")]
    pub counters: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "created_by_user_id", deserialize_with = "Option::deserialize")]
    pub created_by_user_id: Option<String>,
    #[serde(rename = "error_code", deserialize_with = "Option::deserialize")]
    pub error_code: Option<String>,
    #[serde(rename = "error_message_redacted", deserialize_with = "Option::deserialize")]
    pub error_message_redacted: Option<String>,
    #[serde(rename = "finished_at", deserialize_with = "Option::deserialize")]
    pub finished_at: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "idempotency_key")]
    pub idempotency_key: String,
    #[serde(rename = "input_ref")]
    pub input_ref: std::collections::HashMap<String, serde_json::Value>,
    /// Known values: crm_export, crm_delete, crm_activity, sheet_preview, sheet_writeback, notification_delivery, form_ingestion. Clients preserve future values.
    #[serde(rename = "job_type")]
    pub job_type: String,
    #[serde(rename = "lease_expires_at", deserialize_with = "Option::deserialize")]
    pub lease_expires_at: Option<String>,
    #[serde(rename = "lease_owner", deserialize_with = "Option::deserialize")]
    pub lease_owner: Option<String>,
    #[serde(rename = "max_attempts")]
    pub max_attempts: i32,
    #[serde(rename = "next_attempt_at")]
    pub next_attempt_at: String,
    #[serde(rename = "result_ref", deserialize_with = "Option::deserialize")]
    pub result_ref: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "started_at", deserialize_with = "Option::deserialize")]
    pub started_at: Option<String>,
    /// Known values: pending, running, succeeded, failed, cancelled. Clients preserve future values.
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "stream_position")]
    pub stream_position: Box<models::QueuedIntegrationJobStreamPosition>,
    #[serde(rename = "subject_id", deserialize_with = "Option::deserialize")]
    pub subject_id: Option<String>,
    /// Known values: lead, sequence. Clients preserve future values.
    #[serde(rename = "subject_type", deserialize_with = "Option::deserialize")]
    pub subject_type: Option<String>,
    #[serde(rename = "team_id")]
    pub team_id: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl QueuedIntegrationJob {
    pub fn new(attempt: i32, cancel_requested_at: Option<String>, cancel_requested_by_user_id: Option<String>, canonical_event_id: Option<String>, connection_id: String, counters: std::collections::HashMap<String, serde_json::Value>, created_at: String, created_by_user_id: Option<String>, error_code: Option<String>, error_message_redacted: Option<String>, finished_at: Option<String>, id: String, idempotency_key: String, input_ref: std::collections::HashMap<String, serde_json::Value>, job_type: String, lease_expires_at: Option<String>, lease_owner: Option<String>, max_attempts: i32, next_attempt_at: String, result_ref: Option<std::collections::HashMap<String, serde_json::Value>>, started_at: Option<String>, status: String, stream_position: models::QueuedIntegrationJobStreamPosition, subject_id: Option<String>, subject_type: Option<String>, team_id: String, updated_at: String) -> QueuedIntegrationJob {
        QueuedIntegrationJob {
            attempt,
            cancel_requested_at,
            cancel_requested_by_user_id,
            canonical_event_id,
            connection_id,
            counters,
            created_at,
            created_by_user_id,
            error_code,
            error_message_redacted,
            finished_at,
            id,
            idempotency_key,
            input_ref,
            job_type,
            lease_expires_at,
            lease_owner,
            max_attempts,
            next_attempt_at,
            result_ref,
            started_at,
            status,
            stream_position: Box::new(stream_position),
            subject_id,
            subject_type,
            team_id,
            updated_at,
        }
    }
}

