/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotateFreshsalesCredentialRequest {
    #[serde(rename = "apiKey")]
    pub api_key: String,
}

impl RotateFreshsalesCredentialRequest {
    pub fn new(api_key: String) -> RotateFreshsalesCredentialRequest {
        RotateFreshsalesCredentialRequest {
            api_key,
        }
    }
}

