/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SegmentInstallationCreated {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "provider")]
    pub provider: String,
    /// Installation signing secret returned on creation. Store securely; redact from examples and logs.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl SegmentInstallationCreated {
    pub fn new(created_at: String, id: String, label: String, provider: String, secret: String) -> SegmentInstallationCreated {
        SegmentInstallationCreated {
            created_at,
            id,
            label,
            provider,
            secret,
        }
    }
}

