/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SheetWorkflowStateResponse {
    SheetWorkflowResponse(models::SheetWorkflowResponse),
    SheetWorkflowDeleted(models::SheetWorkflowDeleted),
}

impl Default for SheetWorkflowStateResponse {
    fn default() -> Self {
        Self::SheetWorkflowResponse(Default::default())
    }
}

