/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SheetWorkflowPreviewRowsInner {
    /// Input for the workflow capability, built from this spreadsheet row.
    #[serde(rename = "input")]
    pub input: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "rowNumber")]
    pub row_number: i32,
}

impl SheetWorkflowPreviewRowsInner {
    pub fn new(input: std::collections::HashMap<String, serde_json::Value>, row_number: i32) -> SheetWorkflowPreviewRowsInner {
        SheetWorkflowPreviewRowsInner {
            input,
            row_number,
        }
    }
}

