/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SheetWorkflowValidation {
    #[serde(rename = "checkedAt", deserialize_with = "Option::deserialize")]
    pub checked_at: Option<String>,
    #[serde(rename = "code", deserialize_with = "Option::deserialize")]
    pub code: Option<String>,
}

impl SheetWorkflowValidation {
    pub fn new(checked_at: Option<String>, code: Option<String>) -> SheetWorkflowValidation {
        SheetWorkflowValidation {
            checked_at,
            code,
        }
    }
}

