/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SheetWorkflow {
    /// Known values: email.find, email.verify, domain.search. Clients preserve future values.
    #[serde(rename = "capability")]
    pub capability: String,
    /// Validated spreadsheet workflow configuration.
    #[serde(rename = "config")]
    pub config: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "connectionId")]
    pub connection_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "revision")]
    pub revision: i32,
    /// Known values: active, paused. Clients preserve future values.
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "validation")]
    pub validation: models::SheetWorkflowValidation,
}

impl SheetWorkflow {
    pub fn new(capability: String, config: std::collections::HashMap<String, serde_json::Value>, connection_id: String, created_at: String, id: String, label: String, revision: i32, state: String, team_id: String, updated_at: String, validation: models::SheetWorkflowValidation) -> SheetWorkflow {
        SheetWorkflow {
            capability,
            config,
            connection_id,
            created_at,
            id,
            label,
            revision,
            state,
            team_id,
            updated_at,
            validation,
        }
    }
}

