/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SheetWorkflowPreview {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "range")]
    pub range: String,
    #[serde(rename = "rows")]
    pub rows: Vec<models::SheetWorkflowPreviewRowsInner>,
    #[serde(rename = "totalRows")]
    pub total_rows: i32,
    #[serde(rename = "truncated")]
    pub truncated: bool,
    #[serde(rename = "workflow")]
    pub workflow: models::SheetWorkflow,
}

impl SheetWorkflowPreview {
    pub fn new(provider: String, range: String, rows: Vec<models::SheetWorkflowPreviewRowsInner>, total_rows: i32, truncated: bool, workflow: models::SheetWorkflow) -> SheetWorkflowPreview {
        SheetWorkflowPreview {
            provider,
            range,
            rows,
            total_rows,
            truncated,
            workflow,
        }
    }
}

