/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartIntegrationOAuthRequest {
    #[serde(rename = "authorizationServer", skip_serializing_if = "Option::is_none")]
    pub authorization_server: Option<String>,
    #[serde(rename = "resourceUrl", skip_serializing_if = "Option::is_none")]
    pub resource_url: Option<String>,
    #[serde(rename = "returnPath", skip_serializing_if = "Option::is_none")]
    pub return_path: Option<String>,
}

impl StartIntegrationOAuthRequest {
    pub fn new() -> StartIntegrationOAuthRequest {
        StartIntegrationOAuthRequest {
            authorization_server: None,
            resource_url: None,
            return_path: None,
        }
    }
}

