/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateLeadRequest {
    #[serde(rename = "company", skip_serializing_if = "Option::is_none")]
    pub company: Option<models::UpdateLeadRequestCompany>,
    #[serde(rename = "company_addresses", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_addresses: Option<Option<Vec<models::CompanyListResultsInnerAddressesInner>>>,
    #[serde(rename = "company_founded_on", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_founded_on: Option<Option<String>>,
    #[serde(rename = "company_industry", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_industry: Option<Option<String>>,
    #[serde(rename = "company_linkedin", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_linkedin: Option<Option<String>>,
    #[serde(rename = "company_location", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_location: Option<Option<String>>,
    #[serde(rename = "company_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<Option<String>>,
    #[serde(rename = "company_number_of_employees", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_number_of_employees: Option<Option<i32>>,
    #[serde(rename = "company_stock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_stock: Option<Option<String>>,
    #[serde(rename = "company_twitter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_twitter: Option<Option<String>>,
    #[serde(rename = "company_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_type: Option<Option<String>>,
    #[serde(rename = "company_website", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_website: Option<Option<String>>,
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<models::UpdateLeadRequestPerson>,
    #[serde(rename = "person_first_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub person_first_name: Option<Option<String>>,
    #[serde(rename = "person_last_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub person_last_name: Option<Option<String>>,
    #[serde(rename = "person_lead_location", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub person_lead_location: Option<Option<String>>,
    #[serde(rename = "person_linkedin", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub person_linkedin: Option<Option<String>>,
    #[serde(rename = "person_phone_number", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub person_phone_number: Option<Option<String>>,
    #[serde(rename = "person_position", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub person_position: Option<Option<String>>,
    #[serde(rename = "person_twitter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub person_twitter: Option<Option<String>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<String>>>,
}

impl UpdateLeadRequest {
    pub fn new() -> UpdateLeadRequest {
        UpdateLeadRequest {
            company: None,
            company_addresses: None,
            company_founded_on: None,
            company_industry: None,
            company_linkedin: None,
            company_location: None,
            company_name: None,
            company_number_of_employees: None,
            company_stock: None,
            company_twitter: None,
            company_type: None,
            company_website: None,
            person: None,
            person_first_name: None,
            person_last_name: None,
            person_lead_location: None,
            person_linkedin: None,
            person_phone_number: None,
            person_position: None,
            person_twitter: None,
            tags: None,
        }
    }
}

