/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateLeadResponse {
    #[serde(rename = "lead")]
    pub lead: Box<models::UpdateLeadResponseLead>,
}

impl UpdateLeadResponse {
    pub fn new(lead: models::UpdateLeadResponseLead) -> UpdateLeadResponse {
        UpdateLeadResponse {
            lead: Box::new(lead),
        }
    }
}

