/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateIntegrationConnectionStateRequest {
    #[serde(rename = "action")]
    pub action: Action,
}

impl UpdateIntegrationConnectionStateRequest {
    pub fn new(action: Action) -> UpdateIntegrationConnectionStateRequest {
        UpdateIntegrationConnectionStateRequest {
            action,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "pause")]
    Pause,
    #[serde(rename = "resume")]
    Resume,
    #[serde(rename = "disconnect")]
    Disconnect,
}

impl Default for Action {
    fn default() -> Action {
        Self::Pause
    }
}

