/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerificationProgress {
    #[serde(rename = "capabilityEpoch", skip_serializing_if = "Option::is_none")]
    pub capability_epoch: Option<i32>,
    #[serde(rename = "greylistAttempt", skip_serializing_if = "Option::is_none")]
    pub greylist_attempt: Option<i32>,
    #[serde(rename = "invalidationReason", skip_serializing_if = "Option::is_none")]
    pub invalidation_reason: Option<String>,
    #[serde(rename = "mxFingerprint", skip_serializing_if = "Option::is_none")]
    pub mx_fingerprint: Option<String>,
    #[serde(rename = "nextRetryAt", skip_serializing_if = "Option::is_none")]
    pub next_retry_at: Option<String>,
    #[serde(rename = "preferredIp", skip_serializing_if = "Option::is_none")]
    pub preferred_ip: Option<String>,
    #[serde(rename = "reputationGeneration", skip_serializing_if = "Option::is_none")]
    pub reputation_generation: Option<i32>,
    #[serde(rename = "requestId")]
    pub request_id: String,
    /// Known values: clean, dirty. Clients preserve future values.
    #[serde(rename = "requiredTier", skip_serializing_if = "Option::is_none")]
    pub required_tier: Option<String>,
    /// Known values: queued, processing. Clients preserve future values.
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl VerificationProgress {
    pub fn new(request_id: String, state: String, updated_at: String) -> VerificationProgress {
        VerificationProgress {
            capability_epoch: None,
            greylist_attempt: None,
            invalidation_reason: None,
            mx_fingerprint: None,
            next_retry_at: None,
            preferred_ip: None,
            reputation_generation: None,
            request_id,
            required_tier: None,
            state,
            updated_at,
        }
    }
}

